src/objects/AddressBook__c.object
<CustomObject>
    <fields>
        <fullName>abAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Address Books</relationshipLabel>
        <relationshipName>Address_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>abAssetRecordIdentifierKey__c</fullName>
        <label>Asset Record Identifier Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>abCity__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>abCountry__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunei Darussalam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burkina Faso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambodia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cameroon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>abDescription__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>abPostalCode__c</fullName>
        <label>Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>abStateProvince__c</fullName>
        <label>State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>abStreet1__c</fullName>
        <label>Street 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>abStreet2__c</fullName>
        <label>Street 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>abUniqueField__c</fullName>
        <formula>CASESAFEID(abAccount__r.Id) + &apos;_&apos; +
abStreet1__c + &apos;_&apos; +
abStreet2__c + &apos;_&apos; +
abCity__c + &apos;_&apos; +
abStateProvince__c + &apos;_&apos; +
TEXT(abCountry__c) + &apos;_&apos; +
abPostalCode__c</formula>
        <label>Unique Field</label>
        <type>Text</type>
    </fields>
    <label>Address Book</label>
    <nameField>
        <displayFormat>AB-{00000000}</displayFormat>
        <label>Address Book Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/abAssetEntriesBatch.cls
global class abAssetEntriesBatch implements Database.Batchable<sObject>{
   global final String Query;
   //Query all the Asset Address - order by Account,CreatedDate
   ////Inprogress
   global abAssetEntriesBatch(){
               Query='SELECT assetInstallAddressUniqueKey__c,assetPartShipAddressBook__c,Id,Account.Id,Install_City__c, Install_Country__c, Install_Street1__c, Install_Street2__c, Install_State_Province__c,Install_Zip_Code__c,CreatedDate FROM Asset  where Account.ID !=null and (Install_Street1__c != null and Install_City__c != null and Install_Country__c != null) order by Account.Id,CreatedDate';
   }

   global Database.QueryLocator start(Database.BatchableContext BC){
       //Start Method to Execute the query
       return Database.getQueryLocator(query);
   }

   global void execute(Database.BatchableContext BC, 
                       List<sObject> scope){
      
      Set<Id> aAssetIds = new Set<Id>();
      Set<Id> aAccountIds = new Set<Id>();
      Map<String,AddressBook__c> mapAbIncomingRecords = new Map<String,AddressBook__c>();
      Map<String,AddressBook__c> mapExistingAbRecords = new Map<String,AddressBook__c>(); 
                           
      List<AddressBook__c> lstInsertAbRecords = new List<AddressBook__c>();
      List<AddressBook__c> lstUpdateAbRecords = new List<AddressBook__c>();
                           
     
      
       //Loop Through all the incoming records and store it a map                           
       for(sObject s : scope){
            Asset a = (Asset)s;

                   AddressBook__c currentAbRecord = new AddressBook__c();
                   currentAbRecord.abAccount__c = a.Account.Id;
                   currentAbRecord.abStreet1__c = a.Install_Street1__c; 
                   currentAbRecord.abStreet2__c = a.Install_Street2__c;
                   currentAbRecord.abCity__c = a.Install_City__c;
                   currentAbRecord.abStateProvince__c = a.Install_State_Province__c;
                   currentAbRecord.abCountry__c = a.Install_Country__c;
                   currentAbRecord.abPostalCode__c = a.Install_Zip_Code__c; 
                   currentAbRecord.abDescription__c = 'Asset Install Address 1';
                   currentAbRecord.abAssetRecordIdentifierKey__c = a.assetInstallAddressUniqueKey__c;
                   aAssetIds.add(a.Id);
                   mapAbIncomingRecords.put(a.assetInstallAddressUniqueKey__c, currentAbRecord); 
            }
            
            //Check the address already exist in AddressBook
            for (AddressBook__c abs : [SELECT Id, abUniqueField__c,abDescription__c FROM AddressBook__c WHERE abUniqueField__c IN :mapAbIncomingRecords.keySet()]) {
                  mapExistingAbRecords.put(abs.abUniqueField__c,abs);
            }
             
            //Based on the previous step check the record is for Insert/Update
            for (String abIncomingKey : mapAbIncomingRecords.keySet()){
                
                if(mapExistingAbRecords.containsKey(abIncomingKey))
                {
                    AddressBook__c abRecord = mapAbIncomingRecords.get(abIncomingKey);
                    AddressBook__c oldRecord = mapExistingAbRecords.get(abIncomingKey);
                    abRecord.Id = oldRecord.Id;
                    abRecord.abDescription__c = oldRecord.abDescription__c;
                    lstUpdateAbRecords.add(abRecord);
                }
                else
                {
                    AddressBook__c abRecord = mapAbIncomingRecords.get(abIncomingKey);
                    lstInsertAbRecords.add(abRecord); 
                    aAccountIds.add(abRecord.abAccount__c);
                }
            }
            
            //First perform Insert
            insert lstInsertAbRecords;
            //Then perform Update
            update lstUpdateAbRecords;
              
            //Based on the asset Unique Key query the Address Book object              
            Map<String, Id> mapAbAssetKeys = new Map<String, Id>();    
             for (AddressBook__c ab : [SELECT Id, abAssetRecordIdentifierKey__c FROM AddressBook__c WHERE abAssetRecordIdentifierKey__c IN :mapAbIncomingRecords.keySet()]) {
               mapAbAssetKeys.put(ab.abAssetRecordIdentifierKey__c,ab.Id);         
            }

            //Based on the incoming record Asset Id query the Asset Object
            //Check for the RecordIndentifier Address
            //Assign the Address Book to the current Asset              
            List<Asset> lstUpdAssets = new List<Asset>();   
            for (Asset asset : [SELECT Id,assetInstallAddressUniqueKey__c FROM Asset WHERE Id IN:aAssetIds and assetPartShipAddressBook__c=null]) {
                
                Id abId = mapAbAssetKeys.get(asset.assetInstallAddressUniqueKey__c);
                asset.assetPartShipAddressBook__c =abId; 
                lstUpdAssets.add(asset);
                
            }
          
            update lstUpdAssets;

   }

   global void finish(Database.BatchableContext BC){

   }

}