src/objects/AddressBook__c.object
<CustomObject>
    <fields>
        <fullName>abAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Address Books</relationshipLabel>
        <relationshipName>Address_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>abCity__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>abCountry__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunei Darussalam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burkina Faso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambodia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cameroon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>abDescription__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>abPostalCode__c</fullName>
        <label>Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>abStateProvince__c</fullName>
        <label>State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>abStreet1__c</fullName>
        <label>Street 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>abStreet2__c</fullName>
        <label>Street 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address Book</label>
    <nameField>
        <displayFormat>AB-{00000000}</displayFormat>
        <label>Address Book Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/abAssetEntriesBatchTest.cls
@isTest                              
private class abAssetEntriesBatchTest {
    
    static testmethod void testAssetProcessBatch() {
        
        
           Account account;
           List<Account> accounts = new List<Account>();
           List<Id> testAccountIds = new List<Id>();
           
           Asset  asset;          
           List<Asset> assets = new List<Asset>();
        
        
          // Create test Account
           for (Integer i=0;i<5;i++) {
             account = new Account(Name = 'TEST-ACCOUNT' + i);
             accounts.add(account);
           }
        
          insert accounts;
        
          List<Account>  accountLists = [SELECT Id,
                       Name
                FROM   Account order by Name];

          System.assertEquals(accounts.size(),              accountLists.size());
        
          for(Integer i=0;i<accounts.size();i++)
          {
              System.assertEquals('TEST-ACCOUNT' + i,                  accountLists[i].Name, 'Account Name - TEST-ACCOUNT' + i);
              testAccountIds.add(accountLists[i].id);
          }
          
        
        // Create test asset
         for (Integer i=0;i<5;i++) {
           asset = new Asset(Name = 'TEST-ASSET' + i,
                          AccountId = accounts[i].Id,
                          Install_Street1__c        = 'TEST-ASSET-INSTALL-STREET1',
                          Install_Street2__c        = 'TEST-ASSET-INSTALL-STREET2',
                          Install_City__c           = 'TEST-ASSET-INSTALL-CITY',
                          Install_State_Province__c = 'TEST-ASSET-INSTALL-STATE',
                          Install_Country__c        = 'TEST-ASSET-INSTALL-COUNTRY',
                          Install_Zip_Code__c       = 'TEST-ASSET-INSTALL-ZIPCODE');
             assets.add(asset);
         }
        insert assets;
        
         List<Asset>  assetLists = [SELECT Id,
                       Name,
                       AccountId,
                       SLA__c,
                       Install_Street1__c,
                       Install_Street2__c,
                       Install_City__c,
                       Install_Country__c,
                       Install_State_Province__c,
                       Install_Zip_Code__c 
                FROM   Asset order by Name];
        
         System.assertEquals(assets.size(),              assetLists.size());
         
          for(Integer i=0;i<assets.size();i++)
          {
          	  System.assertEquals('TEST-ASSET' + i,                  assetLists[i].Name, 'Asset Name - TEST-ASSET' + i);
              System.assertEquals(accounts[i].id,                 assetLists[i].AccountId,'Asset Name - TEST-ASSET' + i);
              System.assertEquals('TEST-ASSET-INSTALL-STREET1',  assetLists[i].Install_Street1__c,'Asset Name - TEST-ASSET' + i);
              System.assertEquals('TEST-ASSET-INSTALL-STREET2',  assetLists[i].Install_Street2__c,'Asset Name - TEST-ASSET' + i);
              System.assertEquals('TEST-ASSET-INSTALL-CITY',     assetLists[i].Install_City__c,'Asset Name - TEST-ASSET' + i);
              System.assertEquals('TEST-ASSET-INSTALL-STATE',    assetLists[i].Install_State_Province__c,'Asset Name - TEST-ASSET' + i);              
              System.assertEquals('TEST-ASSET-INSTALL-COUNTRY',    assetLists[i].Install_Country__c,'Asset Name - TEST-ASSET' + i);
              System.assertEquals('TEST-ASSET-INSTALL-ZIPCODE',    assetLists[i].Install_Zip_Code__c,'Asset Name - TEST-ASSET' + i);
          }
        
        
        String Query = 'SELECT id,AccountId,Install_City__c, Install_Country__c, Install_Street1__c, Install_Street2__c, Install_State_Province__c,Install_Zip_Code__c,CreatedDate FROM Asset  where Install_Street1__c != null or Install_Street2__c != null or Install_City__c != null or Install_State_Province__c != null or Install_Country__c != null or Install_Zip_Code__c != null order by AccountId,CreatedDate desc';
        Test.startTest();
        AbAssetEntriesBatch e = new AbAssetEntriesBatch();
        Database.executeBatch(e);
        Test.stopTest();   
        
       // Verify Adress Book for the Records Inserted with Description Unique Name
       List<AddressBook__c> ab = [SELECT abAccount__c,abAccount__r.Name,abStreet1__c,abStreet2__c,abCity__c,abStateProvince__c,abCountry__c,abPostalCode__c,abDescription__c FROM AddressBook__c order by abAccount__c,abDescription__c];
       
        System.assertEquals(5,ab.size());
        
       for(Integer i=0;i<ab.size();i++)
          {
              Integer uniqueAddressCount = i + 1;
              System.assertEquals(accounts[i].id,                 ab[i].abAccount__c,'AB Account Name - ' + ab[i].abAccount__r.Name);
              System.assertEquals('TEST-ASSET-INSTALL-STREET1',  ab[i].abStreet1__c,'AB Account Name - ' + ab[i].abAccount__r.Name);
              System.assertEquals('TEST-ASSET-INSTALL-STREET2',  ab[i].abStreet2__c,'AB Account Name - ' + ab[i].abAccount__r.Name);
              System.assertEquals('TEST-ASSET-INSTALL-CITY',     ab[i].abCity__c,'AB Account Name - ' + ab[i].abAccount__r.Name);
              System.assertEquals('TEST-ASSET-INSTALL-STATE',    ab[i].abStateProvince__c,'AB Account Name - ' + ab[i].abAccount__r.Name);             
              System.assertEquals('TEST-ASSET-INSTALL-COUNTRY',    ab[i].abCountry__c,'AB Account Name - ' + ab[i].abAccount__r.Name);
              System.assertEquals('TEST-ASSET-INSTALL-ZIPCODE',    ab[i].abPostalCode__c,'AB Account Name - ' + ab[i].abAccount__r.Name);
          }
        
         // Verify the updated Asset gets the Ship Address Book Entry
         assetLists = [SELECT  Name,
                       AccountId,
                       SLA__c,
                       Install_Street1__c,
                       Install_Street2__c,
                       Install_City__c,
                       Install_Country__c,
                       Install_State_Province__c,
                       Install_Zip_Code__c,
                       assetPartShipAddressBook__c
                FROM   Asset order by Name];
        
         System.assertEquals(assets.size(),              assetLists.size());
         
          for(Integer i=0;i<assets.size();i++)
          {
          	  System.assertEquals('TEST-ASSET' + i,                  assetLists[i].Name, 'Asset Name - TEST-ASSET' + i);
              System.assertEquals(accounts[i].id,                 assetLists[i].AccountId,'Asset Name - TEST-ASSET' + i);
              System.assertEquals('TEST-ASSET-INSTALL-STREET1',  assetLists[i].Install_Street1__c,'Asset Name - TEST-ASSET' + i);
              System.assertEquals('TEST-ASSET-INSTALL-STREET2',  assetLists[i].Install_Street2__c,'Asset Name - TEST-ASSET' + i);
              System.assertEquals('TEST-ASSET-INSTALL-CITY',     assetLists[i].Install_City__c,'Asset Name - TEST-ASSET' + i);
              System.assertEquals('TEST-ASSET-INSTALL-STATE',    assetLists[i].Install_State_Province__c,'Asset Name - TEST-ASSET' + i);              
              System.assertEquals('TEST-ASSET-INSTALL-COUNTRY',    assetLists[i].Install_Country__c,'Asset Name - TEST-ASSET' + i);
              System.assertEquals('TEST-ASSET-INSTALL-ZIPCODE',    assetLists[i].Install_Zip_Code__c,'Asset Name - TEST-ASSET' + i);
              System.assertNotEquals(null, assetLists[i].assetPartShipAddressBook__c,'Asset Name - TEST-ASSET' + i);
          }
        
            
    }
}