src/objects/AddressBook__c.object
<CustomObject>
    <fields>
        <fullName>abAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Address Books</relationshipLabel>
        <relationshipName>Address_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>abCity__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>abCountry__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunei Darussalam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burkina Faso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambodia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cameroon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>abDescription__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>abPostalCode__c</fullName>
        <label>Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>abStateProvince__c</fullName>
        <label>State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>abStreet1__c</fullName>
        <label>Street 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>abStreet2__c</fullName>
        <label>Street 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address Book</label>
    <nameField>
        <displayFormat>AB-{00000000}</displayFormat>
        <label>Address Book Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/abTriggerHandlerTest.cls
@isTest                              
private class abTriggerHandlerTest {
    
    private static ID testAccountId;
    private static ID testAddressBookId;
    
    static testmethod void testCreateAccount() {
        
        Account          account;
        List<Account>    accounts;
        
        
          // Create test account
          account = new Account(Name = 'TEST-ACCOUNT');
          insert account;
          accounts = [SELECT Id,
                             Name
                      FROM   Account
                      WHERE  Name = 'TEST-ACCOUNT'];
    
          System.assertEquals(1,              accounts.size());
          System.assertEquals('TEST-ACCOUNT', accounts[0].Name);
          testAccountId = accounts[0].id;
            
    }
    
    static testmethod void testAbWithDescription() {
        
        testCreateAccount();
        
        AddressBook__c          addressBook;
        List<AddressBook__c>    addressBooks;
        
        
          // Create test AddressBook
          addressBook = new AddressBook__c(abAccount__c = testAccountId,abStreet1__c = 'TEST-STREET1' ,abStreet2__c = 'TEST-STREET2',abCity__c = 'TEST-CITY',abStateProvince__c ='TEST-STATE',abCountry__c='TEST-COUNTRY',abPostalCode__c='1000',abDescription__c='From RMA');
          insert addressBook;
          addressBooks = [SELECT Id,
                             abAccount__c,
                             abStreet1__c,
                             abStreet2__c,
                             abCity__c,
                             abStateProvince__c,
                             abCountry__c,
                             abPostalCode__c,
                             abDescription__c
                      FROM   AddressBook__c];
    
              System.assertEquals(1, addressBooks.size());
              System.assertEquals(testAccountId,                 addressBooks[0].abAccount__c);
              System.assertEquals('TEST-STREET1',  addressBooks[0].abStreet1__c);
              System.assertEquals('TEST-STREET2',  addressBooks[0].abStreet2__c);
              System.assertEquals('TEST-CITY',     addressBooks[0].abCity__c);
              System.assertEquals('TEST-STATE',    addressBooks[0].abStateProvince__c);             
              System.assertEquals('TEST-COUNTRY',    addressBooks[0].abCountry__c);
              System.assertEquals('1000',    addressBooks[0].abPostalCode__c);
              System.assertEquals('From RMA' ,    addressBooks[0].abDescription__c);
              testAddressBookId = addressBooks[0].id;

    }
    
    static testmethod void testAbWithoutDescription() {
        
        testCreateAccount();
        
        AddressBook__c          addressBook;
        List<AddressBook__c>    addressBooks;
        
        
          // Create test AddressBook
          addressBook = new AddressBook__c(abAccount__c = testAccountId,abStreet1__c = 'TEST-STREET1' ,abStreet2__c = 'TEST-STREET2',abCity__c = 'TEST-CITY',abStateProvince__c ='TEST-STATE',abCountry__c='TEST-COUNTRY',abPostalCode__c='1000');
          insert addressBook;
          addressBooks = [SELECT Id,
                             abAccount__c,
                             abStreet1__c,
                             abStreet2__c,
                             abCity__c,
                             abStateProvince__c,
                             abCountry__c,
                             abPostalCode__c,
                             abDescription__c
                      FROM   AddressBook__c];
    
              System.assertEquals(1, addressBooks.size());
              System.assertEquals(testAccountId,                 addressBooks[0].abAccount__c);
              System.assertEquals('TEST-STREET1',  addressBooks[0].abStreet1__c);
              System.assertEquals('TEST-STREET2',  addressBooks[0].abStreet2__c);
              System.assertEquals('TEST-CITY',     addressBooks[0].abCity__c);
              System.assertEquals('TEST-STATE',    addressBooks[0].abStateProvince__c);             
              System.assertEquals('TEST-COUNTRY',    addressBooks[0].abCountry__c);
              System.assertEquals('1000',    addressBooks[0].abPostalCode__c);
              System.assertEquals('Asset Install Address 1' ,    addressBooks[0].abDescription__c);
              testAddressBookId = addressBooks[0].id;

    }

}