src/objects/caseEscalation__c.object
<CustomObject>
    <fields>
        <fullName>caseEscalationCase__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Escalations</relationshipLabel>
        <relationshipName>Case_Escalations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>caseEscalationTypeDefinition__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Case Escalation Type Definition</label>
        <referenceTo>caseEscalationTypeDefinition__c</referenceTo>
        <relationshipLabel>Case Escalations</relationshipLabel>
        <relationshipName>Case_Escalations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Case Escalation</label>
    <nameField>
        <displayFormat>ESC-{000000}</displayFormat>
        <label>Case Escalation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Escalations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/caseEscalationTypeDefinition__c.object
<CustomObject>
    <fields>
        <fullName>caseEscalationTypeDefinitionGroup__c</fullName>
        <label>Group</label>
        <picklist>
            <picklistValues>
                <fullName>Engineering Consult</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering Escalation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Escalation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PEAK Escalation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Escalation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>caseEscalationTypeDefinitionUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_Escalation_Type_Definitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Escalation Type Definition</label>
    <nameField>
        <label>Case Escalation Type Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Escalation Type Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/caseEscalationTriggerTest.cls
@isTest
private class caseEscalationTriggerTest
  {// ==================================================================================== testGood
   static testMethod void testGood()
     {// ===== Create test Case
      Case testCase;
      List<Case> testCases;
      Id testCaseId;

      testCase = new Case(Subject = 'TEST-CASE-SUBJECT');

      insert(testCase);

      testCases = [SELECT Id,
                          Subject
                   FROM   Case
                   WHERE  Subject = 'TEST-CASE-SUBJECT'];

      testCaseId = testCases[0].id;

      // ===== Create test Case Escalation Type Definition
      caseEscalationTypeDefinition__c testCaseEscalationTypeDefinition;
      List<caseEscalationTypeDefinition__c> caseEscalationTypeDefinitions;
      Id testCaseEscalationTypeDefinitionId;

      testCaseEscalationTypeDefinition = new caseEscalationTypeDefinition__c(caseEscalationTypeDefinitionGroup__c = 'Engineering Escalation',
                                                                             caseEscalationTypeDefinitionUser__c  = null);

      insert(testCaseEscalationTypeDefinition);

      caseEscalationTypeDefinitions = [SELECT Id,
                                              Name,
                                              caseEscalationTypeDefinitionGroup__c,
                                              caseEscalationTypeDefinitionUser__c
                                       FROM   caseEscalationTypeDefinition__c];

      testCaseEscalationTypeDefinitionId = caseEscalationTypeDefinitions[0].Id;

      // ===== Create test Case Escalation
      caseEscalation__c testCaseEscalation;
      List<caseEscalation__c> caseEscalations;

      testCaseEscalation = new caseEscalation__c(caseEscalationCase__c = testCaseId,
                                                 caseEscalationTypeDefinition__c = testCaseEscalationTypeDefinitionId);

      insert(testCaseEscalation);

      caseEscalations = [SELECT Id,
                                caseEscalationCase__c,
                                caseEscalationTypeDefinition__c
                         FROM   caseEscalation__c];

      System.assertEquals(1,                                  caseEscalations.size());
      System.assertEquals(testCaseId,                         caseEscalations[0].caseEscalationCase__c);
      System.assertEquals(testCaseEscalationTypeDefinitionId, caseEscalations[0].caseEscalationTypeDefinition__c);

      testCases = [SELECT Id,
                          caseEscalationType__c
                   FROM   Case
                   WHERE  Id = :testCaseId];

      System.assertEquals('Engineering Escalation', testCases[0].caseEscalationType__c);
     }

// ==================================================================================== testBad_Duplicate
   static testMethod void testBad_Duplicate()
     {// ===== Create test Case
      Case testCase;
      List<Case> testCases;
      Id testCaseId;

      testCase = new Case(Subject = 'TEST-CASE-SUBJECT');

      insert(testCase);

      testCases = [SELECT Id,
                          Subject
                   FROM   Case
                   WHERE  Subject = 'TEST-CASE-SUBJECT'];

      testCaseId = testCases[0].id;

      // ===== Create test Case Escalation Type Definition
      caseEscalationTypeDefinition__c testCaseEscalationTypeDefinition;
      List<caseEscalationTypeDefinition__c> caseEscalationTypeDefinitions;
      Id testCaseEscalationTypeDefinitionId;

      testCaseEscalationTypeDefinition = new caseEscalationTypeDefinition__c(caseEscalationTypeDefinitionGroup__c = 'Engineering Escalation',
                                                                             caseEscalationTypeDefinitionUser__c  = null);

      insert(testCaseEscalationTypeDefinition);

      caseEscalationTypeDefinitions = [SELECT Id,
                                              Name,
                                              caseEscalationTypeDefinitionGroup__c,
                                              caseEscalationTypeDefinitionUser__c
                                       FROM   caseEscalationTypeDefinition__c];

      testCaseEscalationTypeDefinitionId = caseEscalationTypeDefinitions[0].Id;

      // ===== Create test Case Escalation
      caseEscalation__c testCaseEscalation;
      List<caseEscalation__c> caseEscalations;

      testCaseEscalation = new caseEscalation__c(caseEscalationCase__c           = testCaseId,
                                                 caseEscalationTypeDefinition__c = testCaseEscalationTypeDefinitionId);

      insert(testCaseEscalation);

      caseEscalations = [SELECT Id,
                                caseEscalationCase__c,
                                caseEscalationTypeDefinition__c
                         FROM   caseEscalation__c];

      System.assertEquals(1,                                  caseEscalations.size());
      System.assertEquals(testCaseId,                         caseEscalations[0].caseEscalationCase__c);
      System.assertEquals(testCaseEscalationTypeDefinitionId, caseEscalations[0].caseEscalationTypeDefinition__c);

      // ===== Create duplicate test Case Escalation
      caseEscalation__c testCaseEscalation2;
      List<caseEscalation__c> caseEscalations2;
      Exception dmlException;

      testCaseEscalation2 = new caseEscalation__c(caseEscalationCase__c           = testCaseId,
                                                  caseEscalationTypeDefinition__c = testCaseEscalationTypeDefinitionId);

      try
        {insert(testCaseEscalation2);
        }
      catch(Exception ex)
        {dmlException = ex;
        }

      System.assertNotEquals(null, dmlException);
      System.assert(dmlException instanceOf system.Dmlexception);
      System.assert(dmlException.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
      System.assert(dmlException.getMessage().contains('ERROR: There is already a Case Escalation with this Case Number and Escalation Type (Group/User).'));
     }
  }