src/objects/Category_Notes__c.object
<CustomObject>
    <fields>
        <fullName>Article_Ids__c</fullName>
        <description>Article Id&apos;s in this field will be updated by Peak TSE team</description>
        <label>Article Ids</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Category Note</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Category Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Category Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KB_Article__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Article</label>
    <pluralLabel>Articles</pluralLabel>
</CustomObject>

src/classes/KBArticleDisplayController.cls
public class KBArticleDisplayController 
{
public List<KBType> kbTypes{get;set;}
public Category_Notes__c cn;
public KBArticleDisplayController(ApexPages.StandardController stdController)
{
kbTypes = new List<KBType>();
cn = (Category_Notes__c)stdController.getRecord();
cn = [select Id, Article_Ids__c from Category_Notes__c where Id =: cn.Id];
Set<String> artIdSet = new Set<String>();
if(cn.Article_Ids__c != null)
{
List<String> artIds = cn.Article_Ids__c.split(':');
artIdSet.addAll(artIds);
}
List<KB_Article__kav> kbarticles = [SELECT Id,KnowledgeArticleId, Title FROM KB_Article__kav where PublishStatus = 'Online' AND language ='en_US' and KnowledgeArticleId in :artIdSet];
for(KB_Article__kav kb : kbarticles)
{
KBType kt = new KBType();
kt.title = kb.Title;
kt.kbId = kb.KnowledgeArticleId;
kbTypes.add(kt);
}
}
public class KBType
{
public String kbId{get;set;}
public String title{get;set;}
}

}