src/objects/Category_Notes__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <description>Category values are fetched from Case Object Category</description>
        <label>Category</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>This field will be populated by TSE Peak team for given Category and Sub Category. 
During Case creation TSE selects Cat and Sub-Cat, a comment will be created under Case related list.</description>
        <inlineHelpText>This field will be populated by TSE Peak team for given Category and Sub Category. 
During Case creation TSE selects Cat and Sub-Cat, a comment will be created under Case related list.</inlineHelpText>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <description>The Sub Category will be fetched from the field Sub Category of Case Object.</description>
        <label>Sub Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Category Note</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Category Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Category Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestCategoryNotesNewController.cls
@isTest
public class TestCategoryNotesNewController 
{
static testMethod void testCategoryNotesAddndUpdate()
{
    //Insert new category notes
    Category_Notes__c cn = new Category_Notes__c(Notes__c='Question 1:');
    ApexPages.StandardController sc = new ApexPages.StandardController(cn);
    CategoryNotesNewController cnctrl = new CategoryNotesNewController(sc);
    PageReference pageRef = Page.CategoryNotesNewPage;
    Test.setCurrentPage(pageRef);
    Case c = new Case(casecatcategory__c='Backup Integration',casesubcategory__c='CommVault');
    cnctrl.c = c;
    cnctrl.cn = cn;
	cnctrl.saveCategoryUserOnInsert();  
    List<Category_Notes__c> cnNewList = [select Id, Category__c, Sub_Category__c, Notes__c from Category_Notes__c];
    System.assertEquals(1,cnNewList.size());
    Category_Notes__c cnNew = cnNewList.get(0);
    System.assertEquals('Backup Integration',cnNew.Category__c);
    System.assertEquals('CommVault',cnNew.Sub_Category__c);
    System.assertEquals('Question 1:',cnNew.Notes__c);
    
    //Update category notes
    ApexPages.StandardController sc1 = new ApexPages.StandardController(cnNew);
    CategoryNotesNewController cnctrl1 = new CategoryNotesNewController(sc1);
    PageReference pageRef1 = Page.CategoryNotesEditPage;
    Test.setCurrentPage(pageRef1);
    Case c1 = new Case(casecatcategory__c='Cisco UCS Integration',casesubcategory__c='Boot from SAN');
    cnctrl1.c = c1;
    cnctrl1.cn = cnNew;
	cnctrl1.saveCategoryUserOnUpdate();  
    List<Category_Notes__c> cnUpdateList = [select Id, Category__c, Sub_Category__c, Notes__c from Category_Notes__c];
    System.assertEquals(1,cnUpdateList.size());
    Category_Notes__c cnUpdate = cnUpdateList.get(0);
    System.assertEquals('Cisco UCS Integration',cnUpdate.Category__c);
    System.assertEquals('Boot from SAN',cnUpdate.Sub_Category__c);
    System.assertEquals('Question 1:',cnUpdate.Notes__c);
    
}
}