src/objects/Category_Notes__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <description>Category values are fetched from Case Object Category</description>
        <label>Category</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>This field will be populated by TSE Peak team for given Category and Sub Category. 
During Case creation TSE selects Cat and Sub-Cat, a comment will be created under Case related list.</description>
        <inlineHelpText>This field will be populated by TSE Peak team for given Category and Sub Category. 
During Case creation TSE selects Cat and Sub-Cat, a comment will be created under Case related list.</inlineHelpText>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <description>The Sub Category will be fetched from the field Sub Category of Case Object.</description>
        <label>Sub Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Category Note</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Category Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Category Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CategoryNotesNewController.cls
public class CategoryNotesNewController 
{
    public Case c{get;set;}
    public Category_Notes__c cn{get;set;}
    public CategoryNotesNewController(ApexPages.StandardController stdController)
    {
        this.cn = (Category_Notes__c)stdController.getRecord();
        if(this.cn == null)
        {
             c = new case(casecatCategory__c='', casesubcategory__c ='');
             cn = new Category_Notes__C();// added
        }
        else
        {
            List<Category_Notes__c> cnList = [select Id, Category__c,sub_category__c, notes__c from Category_Notes__c where Id =: cn.Id];
            if(cnList.size() > 0)
            {
                cn = cnList.get(0);
             	c = new case(casecatcategory__c=cn.Category__c, casesubcategory__c = cn.Sub_Category__c );
            }
            else
            {
                c = new case(casecatcategory__c='',casesubcategory__c ='');
                cn = new Category_Notes__C();// added
            }
        }
    }
    public PageReference saveCategoryUserOnInsert()
    {
        cn.Category__c=c.casecatCategory__c; //added
        cn.Sub_Category__c=c.caseSubCategory__c;//added
        insert cn;
        PageReference pg = new PageReference('/' + cn.Id);
        return pg;
    }
    public PageReference saveCategoryUserOnUpdate()
    { 
        cn.Category__c=c.casecatCategory__c;
        cn.Sub_Category__c=c.caseSubCategory__c;
        update cn;
        PageReference pg = new PageReference('/' + cn.Id);
        return pg;
    }

}