src/objects/Category_Notes__c.object
<CustomObject>
    <fields>
        <fullName>Article_Ids__c</fullName>
        <description>Article Id&apos;s in this field will be updated by Peak TSE team</description>
        <label>Article Ids</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Category values are fetched from Case Object Category</description>
        <label>Category</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>This field will be populated by TSE Peak team for given Category and Sub Category. 
During Case creation TSE selects Cat and Sub-Cat, a comment will be created under Case related list.</description>
        <inlineHelpText>This field will be populated by TSE Peak team for given Category and Sub Category. 
During Case creation TSE selects Cat and Sub-Cat, a comment will be created under Case related list.</inlineHelpText>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <description>The Sub Category will be fetched from the field Sub Category of Case Object.</description>
        <label>Sub Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Category Note</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Category Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Category Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KB_Article__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Article</label>
    <pluralLabel>Articles</pluralLabel>
</CustomObject>

src/classes/TestKBArticleController.cls
@isTest(SeeAllData=true)
public class TestKBArticleController 
{

    static testMethod void testKBArticleForCatAndSubCat()
    {
        Category_Notes__c cn = new Category_Notes__c(Notes__c='Question1:',Category__c='Cisco UCS Integration',Sub_Category__c='Boot from SAN');
        insert cn;
        KB_Article__kav kb = [select Id, KnowledgeArticleId, title from KB_Article__kav where PublishStatus = 'Online' AND language ='en_US' limit 1];
        //Test the KBArticleAddPage
        ApexPages.StandardController sc = new ApexPages.StandardController(cn);
        KBArticleAddController cnctrl = new KBArticleAddController(sc);
        PageReference pageRef = Page.KBArticleAddPage;
        Test.setCurrentPage(pageRef);
        cnctrl.cn = cn;
        KBArticleAddController.KBType kbType = new KBArticleAddController.KBType();
        kbType.kbId = kb.KnowledgeArticleId;
        kbType.title = kb.Title;
        kbType.include = true;
        List<KBArticleAddController.KBType> kbTypes = new List<KBArticleAddController.KBType>();
        kbTypes.add(kbType);
        cnctrl.kbTypes = kbTypes;
        PageReference pgref = cnctrl.saveKBArticles();
        Category_Notes__c cn1 = [select Id, Article_Ids__c from Category_Notes__c where id =: cn.Id];
        System.assertEquals(kb.KnowledgeArticleId + ':', cn1.Article_Ids__c);
        System.assertEquals(pgref.getUrl(),'/' + cn.Id);
        
        //Test the KBArticleDisplayPage
        ApexPages.StandardController sc1 = new ApexPages.StandardController(cn);
        KBArticleDisplayController cnctrl1 = new KBArticleDisplayController(sc1);
        PageReference pageRef1 = Page.KBArticleDisplayPage;
        Test.setCurrentPage(pageRef1);
        
        //Test the CaseKBArticlePage
        Case c = new Case(casecatcategory__c='Cisco UCS Integration',casesubcategory__c='Boot from SAN');
        insert c;
        ApexPages.StandardController sc2 = new ApexPages.StandardController(c);
        CaseKBArticleController cnctrl2 = new CaseKBArticleController(sc2);
        PageReference pageRef2 = Page.CaseKBArticlePage;
        Test.setCurrentPage(pageRef2);
        cnctrl2.c = c;
    }
}