src/objects/CntrbnMdl_CaseBacklog__c.object
<CustomObject>
    <description>This object allows you to store the data for cumulative case backlog of each TSE on daily basis</description>
    <fields>
        <fullName>Batch_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Batch Count</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cumulative_Backlog__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cumulative Backlog</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CntrbnMdl_CaseBacklogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contribution Model CaseBacklog</label>
    <nameField>
        <displayFormat>CB-{0000000}</displayFormat>
        <label>CaseBacklog_Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contribution Model CaseBacklogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CntrbnMdl_ContributionData__c.object
<CustomObject>
    <description>This object allows you to store the data for support contribution of each TSE on monthly basis.</description>
    <fields>
        <fullName>Call_Hold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Avg_Call Hold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Calls__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Avg_Calls</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Case_Backlog__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Case Backlog</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Case_Modifier__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Case Modifier</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cases__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Closed Cases</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Difficulty__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Difficulty</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Escalated__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Escalated</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KBs_Reviewed__c</fullName>
        <defaultValue>0</defaultValue>
        <label>KBs Reviewed</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KBs_Written__c</fullName>
        <defaultValue>0</defaultValue>
        <label>KBs Written</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Peer_Cases__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Peer Cases</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Projects__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Projects</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TSE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TSE</label>
        <referenceTo>CntrbnMdl_TSE__c</referenceTo>
        <relationshipName>Contribution_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Talk_Time__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Avg_Talk Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Training_Dev__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Training_Dev</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Training_Lead__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Training Lead</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Contribution Model Data</label>
    <nameField>
        <displayFormat>CDN-{0000000}</displayFormat>
        <label>Contribution Data Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contribution Model Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CntrbnMdl_Jive__c.object
<CustomObject>
    <fields>
        <fullName>ActiveCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ActiveCount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ContributingCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ContributingCount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ParticipatingCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ParticipatingCount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CntrbnMdl_Jive</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contribution Model Jive</label>
    <nameField>
        <displayFormat>JN-{0000000}</displayFormat>
        <label>Jive Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contribution Model Jive</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CntrbnMdl_Project__c.object
<CustomObject>
    <description>This object allows you to store the data for project contribution of each TSE on monthly basis</description>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Project_Hours</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CntrbnMdl_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contribution Model Project</label>
    <nameField>
        <displayFormat>PN-{0000000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contribution Model Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CntrbnMdl_PTO__c.object
<CustomObject>
    <description>This object allows you to store the data for PTO of each TSE on monthly basis</description>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_days_off__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of days off</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CntrbnMdl_PTO</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contribution Model PTO</label>
    <nameField>
        <displayFormat>PTO-{0000000}</displayFormat>
        <label>PTO_Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contribution Model PTO</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CntrbnMdl_ShoreTelCallLog__c.object
<CustomObject>
    <description>This object allows you to store the data for Shoretelcall contribution of each TSE on monthly basis</description>
    <fields>
        <fullName>Avg_Call_Hold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Avg_Call_Hold</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Avg_Calls__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Avg_Calls</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Avg_Talk_Time__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Avg_Talk_Time</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CntrbnMdl_ShoreTelCallLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contribution Model ShoreTelCallLog</label>
    <nameField>
        <displayFormat>STCLN-{0000000}</displayFormat>
        <label>ShoreTelCallLog Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contribution Model ShoreTelCallLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CntrbnMdl_Training__c.object
<CustomObject>
    <description>This object allows you to store the data for Training contribution of each TSE on monthly basis</description>
    <fields>
        <fullName>Development_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Development Hours</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Lead Hours</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CntrbnMdl_Training</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contribution Model Training</label>
    <nameField>
        <displayFormat>TN-{0000000}</displayFormat>
        <label>Training Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contribution Model Training</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CntrbnMdl_TSE__c.object
<CustomObject>
    <description>This object allows you to store data for the personnel information about TSE</description>
    <fields>
        <fullName>Employee_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CSE</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <picklist>
            <picklistValues>
                <fullName>PEAK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <picklist>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RTP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contribution Model TSE</label>
    <nameField>
        <displayFormat>TSE-{0000000}</displayFormat>
        <label>TSE Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contribution Model TSE</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CntrbnMdl_DataCreatorTestClass.cls
@isTest(SeeAllData = true)
public class CntrbnMdl_DataCreatorTestClass{
    public static String CRON_EXP = '0 0 0 15 3 ? 2022';
    public static testMethod void DataCreatortest(){
        ID ProfileID = [ Select id from Profile where name = 'System Administrator'].id;
        User u = new User(email='test-user@example1.com',profileid = ProfileID, 
                             UserName='test-user@email.com',alias='tuser1',CommunityNickName='tuser',TimeZoneSidKey='America/New_York', 
                             LocaleSidKey='en_US',EmailEncodingKey='ISO-8859-1',LanguageLocaleKey='en_US', 
                             FirstName = 'Test',LastName = 'UserTest' );
        insert u;
        User u2 = new User(email='test-user@example1.com',profileid = ProfileID, 
                             UserName='test-user2@email.com',alias='tuser12',CommunityNickName='tuser2',TimeZoneSidKey='America/New_York', 
                             LocaleSidKey='en_US',EmailEncodingKey='ISO-8859-1',LanguageLocaleKey='en_US', 
                             FirstName = 'Test2',LastName = 'UserTest2' );
        insert u2;
        CntrbnMdl_TSE__c tse = new CntrbnMdl_TSE__c(Employee_Name__c = u.id,team__c='HQ',organization__c='TSE');
        insert tse;
        CntrbnMdl_TSE__c tse2 = new CntrbnMdl_TSE__c(Employee_Name__c = u2.id,team__c='HQ',organization__c='TSE');
        insert tse2;
        ID SProfileID = [ Select id from Profile where name = 'Support: System Administrator'].id;
        User usr = new User(email='contest-user@example1.com',profileid = SProfileID, 
                      UserName='test-user25@email.com',alias='tuser25',CommunityNickName='tuser25',TimeZoneSidKey='America/New_York', 
                      LocaleSidKey='en_US',EmailEncodingKey='ISO-8859-1',LanguageLocaleKey='en_US', 
                      FirstName = 'Test25',LastName = 'UserTest25' );
        insert usr;
        System.runAs(usr) {
            RecordType suprectype = [select id,Name from RecordType where SobjectType='Account' and Name='Support Provider' Limit 1];
            RecordType chrectype = [select id,Name from RecordType where SobjectType='Account' and Name='Channel' Limit 1];
            Account serviceAccount = new Account(Name = 'conmodeltest',Type = 'Support Provider',RecordTypeId = suprectype.id);
            insert serviceAccount;
            Account account = new Account(Name = 'conmodeltest2',Type = 'Customer',RecordTypeId = chrectype.id,Support_Provider__c = serviceAccount.id);
            insert account;
            Case caseRec = new Case(Status = 'new',AccountId = account.Id);
            insert caseRec;
        }    
        CntrbnMdl_ShoreTelCallLog__c shoretel = new CntrbnMdl_ShoreTelCallLog__c(User__c = u.id,Month__c = system.today(),Avg_Calls__c = 10, Avg_Call_Hold__c=10, Avg_Talk_Time__c=10);
        insert shoretel;
        CntrbnMdl_Project__c prj = new CntrbnMdl_Project__c(User__c = u.id,Month__c = system.today(),Project_Hours__c=10);
        insert prj;
        CntrbnMdl_PTO__c pto = new CntrbnMdl_PTO__c(User__c = u.id,Month__c = system.today(),Number_of_days_off__c=10);
        insert pto;
        CntrbnMdl_Training__c trn = new CntrbnMdl_Training__c(User__c = u.id,Month__c = system.today(),Development_Hours__c=10,Lead_Hours__c=10);
        insert trn;
        CntrbnMdl_CaseBacklog__c cb = new CntrbnMdl_CaseBacklog__c(User__c = u.id,Month__c = system.today(),Cumulative_Backlog__c=100,Batch_Count__c=10);
        insert cb;
        CntrbnMdl_Jive__c jv = new CntrbnMdl_Jive__c(User__c = u.id,Month__c = system.today(),ActiveCount__c=5,ContributingCount__c=6,ParticipatingCount__c=7);
        insert jv;
        CntrbnMdl_ContributionData__c con = new CntrbnMdl_ContributionData__c(TSE__c = tse.id,Call_Hold__c=10,Calls__c=10,Talk_Time__c=10,Case_Modifier__c=10,Case_Backlog__c=10,Cases__c=10,Difficulty__c=10,
                                                 Escalated__c=10,KBs_Reviewed__c=10,KBs_Written__c=10,Peer_Cases__c=10,Projects__c=10,Training_Dev__c=10,Training_Lead__c=10,Start_Date__c=Date.parse('5/1/2014'),end_Date__c=Date.parse('5/31/2014') );
        insert con;
        system.debug('+++con+++'+con);
        CntrbnMdl_ContributionData__c con2 = new CntrbnMdl_ContributionData__c(TSE__c = tse2.id,Call_Hold__c=10,Calls__c=10,Talk_Time__c=10,Case_Modifier__c=10,Case_Backlog__c=10,Cases__c=10,Difficulty__c=10,
                                                 Escalated__c=10,KBs_Reviewed__c=10,KBs_Written__c=10,Peer_Cases__c=10,Projects__c=10,Training_Dev__c=10,Training_Lead__c=10,Start_Date__c=Date.parse('5/1/2014'),end_Date__c=Date.parse('5/31/2014') );
        insert con2;
        CntrbnMdl_ContributionData__c con3 = new CntrbnMdl_ContributionData__c(TSE__c = tse2.id,Call_Hold__c=10,Calls__c=10,Talk_Time__c=10,Case_Modifier__c=10,Case_Backlog__c=10,Cases__c=10,Difficulty__c=10,
                                                 Escalated__c=10,KBs_Reviewed__c=10,KBs_Written__c=10,Peer_Cases__c=10,Projects__c=10,Training_Dev__c=10,Training_Lead__c=10,Start_Date__c=system.today().toStartOfMonth(),end_Date__c=system.today()-1 );
        insert con3;
        Test.startTest();
          CntrbnMdl_CntrbnDataCreator  CDC = new CntrbnMdl_CntrbnDataCreator ();
          //Database.executeBatch(CDC);
         // String jobId = System.schedule('CntrbnMdl_CntrbnDataCreatorSchedular',CRON_EXP,new CntrbnMdl_CntrbnDataCreatorSchedular());
        Test.stopTest();
       
    }
}