src/objects/CntrbnMdl_TSE__c.object
<CustomObject>
    <description>This object allows you to store data for the personnel information about TSE</description>
    <fields>
        <fullName>DateTime_Eastern__c</fullName>
        <label>DateTime(Eastern)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Datetime_GMT__c</fullName>
        <label>Datetime(GMT)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Datetime_Pacific__c</fullName>
        <label>Datetime(Pacific)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Datetime_Singapore__c</fullName>
        <label>Datetime(Singapore)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enter_Starttime__c</fullName>
        <label>Enter Starttime</label>
        <type>DateTime</type>
    </fields>
    <label>Contribution Model TSE</label>
    <nameField>
        <displayFormat>TSE-{0000000}</displayFormat>
        <label>TSE Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contribution Model TSE</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_CntrbnMdlTSETrigger.cls
@isTest
public class Test_CntrbnMdlTSETrigger 
{
    
    static testMethod void testTSETimeZoneConversion()
    {
        CntrbnMdl_TSE__c tse = new CntrbnMdl_TSE__c();       
        insert tse;
        tse.Enter_Starttime__c = System.now();
        update tse;
        CntrbnMdl_TSE__c utse = [select Id, DateTime_Eastern__c, Datetime_GMT__c, Datetime_Pacific__c, Datetime_Singapore__c from CntrbnMdl_TSE__c where Id =:tse.Id];
        System.assertnotEquals(utse.DateTime_Eastern__c,null);
        System.assertnotEquals(utse.Datetime_GMT__c,null);
        System.assertnotEquals(utse.Datetime_Pacific__c,null);
        System.assertnotEquals(utse.Datetime_Singapore__c,null);        
    }

}