src/objects/CntrbnMdl_Jive__c.object
<CustomObject>
    <fields>
        <fullName>ActiveCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ActiveCount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ContributingCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ContributingCount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ParticipatingCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ParticipatingCount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CntrbnMdl_Jive</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contribution Model Jive</label>
    <nameField>
        <displayFormat>JN-{0000000}</displayFormat>
        <label>Jive Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contribution Model Jive</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CntrbnMdl_Project__c.object
<CustomObject>
    <description>This object allows you to store the data for project contribution of each TSE on monthly basis</description>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Project_Hours</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CntrbnMdl_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contribution Model Project</label>
    <nameField>
        <displayFormat>PN-{0000000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contribution Model Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CntrbnMdl_PTO__c.object
<CustomObject>
    <description>This object allows you to store the data for PTO of each TSE on monthly basis</description>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_days_off__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of days off</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CntrbnMdl_PTO</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contribution Model PTO</label>
    <nameField>
        <displayFormat>PTO-{0000000}</displayFormat>
        <label>PTO_Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contribution Model PTO</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CntrbnMdl_ShoreTelCallLog__c.object
<CustomObject>
    <description>This object allows you to store the data for Shoretelcall contribution of each TSE on monthly basis</description>
    <fields>
        <fullName>Avg_Call_Hold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Avg_Call_Hold</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Avg_Calls__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Avg_Calls</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Avg_Talk_Time__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Avg_Talk_Time</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CntrbnMdl_ShoreTelCallLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contribution Model ShoreTelCallLog</label>
    <nameField>
        <displayFormat>STCLN-{0000000}</displayFormat>
        <label>ShoreTelCallLog Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contribution Model ShoreTelCallLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CntrbnMdl_Training__c.object
<CustomObject>
    <description>This object allows you to store the data for Training contribution of each TSE on monthly basis</description>
    <fields>
        <fullName>Development_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Development Hours</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Lead Hours</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CntrbnMdl_Training</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contribution Model Training</label>
    <nameField>
        <displayFormat>TN-{0000000}</displayFormat>
        <label>Training Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contribution Model Training</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CntrbnMdl_TSECreatorTestClass.cls
@isTest (SeeAllData = true)
public class CntrbnMdl_TSECreatorTestClass{
    public static String CRON_EXP = '0 0 0 15 3 ? 2022';
    public static testMethod void TSECreator(){
        ID ProfileID = [ Select id from Profile where name = 'System Administrator'].id;
        Account acc = new Account (
            Name = 'TestAccount1');
        //insert acc;
        
        List<Contact> ContactList = new List<Contact>();
        Contact con = new Contact( 
            AccountID = acc.id, 
            FirstName = 'Test', 
            LastName = 'UserTest', 
            email = 'test-user@example1.com' );
        //insert con;
 
        User u = new User(email='test-tseuser@example1.com',profileid = ProfileID,isActive = true, 
                             UserName='test-tseuser@email.com',alias='tseuser1',CommunityNickName='tseuser',TimeZoneSidKey='America/New_York', 
                             LocaleSidKey='en_US',EmailEncodingKey='ISO-8859-1',LanguageLocaleKey='en_US', 
                             FirstName = 'rseTest',LastName = 'UserTest' );
        insert u;
        Case caseRecnew = new Case(Status = 'new',AccountId = acc.Id,ownerId = u.id);
        insert caseRecnew;
        CntrbnMdl_ShoreTelCallLog__c shoretel = new CntrbnMdl_ShoreTelCallLog__c(User__c = u.id,Month__c = system.today(),Avg_Calls__c = 10, Avg_Call_Hold__c=10, Avg_Talk_Time__c=10);
        insert shoretel;
        CntrbnMdl_Project__c prj = new CntrbnMdl_Project__c(User__c = u.id,Month__c = system.today(),Project_Hours__c=10);
        insert prj;
        CntrbnMdl_PTO__c pto = new CntrbnMdl_PTO__c(User__c = u.id,Month__c = system.today(),Number_of_days_off__c=10);
        insert pto;
        CntrbnMdl_Training__c trn = new CntrbnMdl_Training__c(User__c = u.id,Month__c = system.today(),Development_Hours__c=10,Lead_Hours__c=10);
        insert trn;
        CntrbnMdl_Jive__c jv = new CntrbnMdl_Jive__c(User__c = u.id,Month__c = system.today(),ActiveCount__c=5,ContributingCount__c=6,ParticipatingCount__c=7);
        insert jv;
       Test.startTest();
          CntrbnMdl_TSECreator c = new CntrbnMdl_TSECreator();
          //Database.executeBatch(c);
          String jobId = System.schedule('CntrbnMdl_TSECreatorSchedular',CRON_EXP,new CntrbnMdl_TSECreatorSchedular());
       Test.stopTest();
    }
    
}