src/objects/Contract_Management__c.object
<CustomObject>
    <description>Object to Capture Nimble Contracts</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Account</description>
        <inlineHelpText>Related Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>NonStandard_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agreement_Name__c</fullName>
        <description>Agreement Name</description>
        <inlineHelpText>Please enter Company/Entity Name</inlineHelpText>
        <label>Entity Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Contract Management</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_ContractManagementInline.cls
@isTest
private class Test_ContractManagementInline {

    static testMethod void myUnitTest() {
        
        Account acc = new Account();
        acc.name='test';
        insert acc;
        
        Contract_Management__c conmgmt = new Contract_Management__c();
        conmgmt.Account__c = acc.id;
        conmgmt.Agreement_Name__c = 'testName';
        insert conmgmt;
        
        Contract_Management__c conmgmt1 = new Contract_Management__c();
        conmgmt.Account__c = acc.id;
        conmgmt.Agreement_Name__c = 'testName';
        update conmgmt;
        
        Contract_Management__c myTestTrainee = [select id from Contract_Management__c limit 1];
        ApexPAges.StandardController sc = new ApexPages.StandardController(myTestTrainee);
        ContractManagementInline conInline = new ContractManagementInline(sc);
        conInline.editBtn();
        conInline.saveBtn();
        conInline.cancelBtn();
        conInline.saveBtnforInline();
        conInline.cancelBtnforInline();
        
    }
}