src/objects/Duplicate_Asset__c.object
<CustomObject>
    <description>Custom Object used as a holding place for the processing of Asset/Support Entitlement data coming from Navision to Salesforce to create Asset Records.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Duplicate Assets</relationshipLabel>
        <relationshipName>Duplicate_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset_Currency__c</fullName>
        <label>Asset Currency</label>
        <picklist>
            <picklistValues>
                <fullName>AUD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GBP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Asset_Name__c</fullName>
        <label>Asset Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Duplicate Assets</relationshipLabel>
        <relationshipName>Duplicate_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Matched_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Matched Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Duplicate Assets</relationshipLabel>
        <relationshipName>Duplicate_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Duplicate Assets</relationshipLabel>
        <relationshipName>Duplicate_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <label>Order Type</label>
        <picklist>
            <picklistValues>
                <fullName>Eval Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Duplicate Assets</relationshipLabel>
        <relationshipName>Duplicate_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Date__c</fullName>
        <formula>IF(ISPICKVAL( Order_Type__c , &apos;Eval Unit&apos; ) , NULL, Sales_Order__r.Approved_Date__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Purchase Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA</label>
        <picklist>
            <picklistValues>
                <fullName>Premium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Premium 4 Hour</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Premium 4 Hour Onsite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSC: Premium Onsite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSC: Premium 4 Hour Onsite</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Duplicate Assets</relationshipLabel>
        <relationshipName>Duplicate_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <label>Serial Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Date__c</fullName>
        <label>Shipping Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Decommissioned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scrapped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Support_End_Date__c</fullName>
        <label>Support End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Support_Start_Date__c</fullName>
        <label>Support Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>assetNrdEndDate__c</fullName>
        <label>NRD End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>assetNrdStartDate__c</fullName>
        <label>NRD Start Date</label>
        <type>Date</type>
    </fields>
    <label>Duplicate Asset</label>
    <nameField>
        <displayFormat>DA-{000000}</displayFormat>
        <label>Duplicate Asset ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Duplicate Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to OA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved by OA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by OA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order in Process</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/schedule_batch_duplicate_rec.cls
global class schedule_batch_duplicate_rec implements Schedulable {

global void execute(SchedulableContext sc)
    {
    	String query='Select id,Serial_Number__c,Account__c,Contact__c,Asset_Name__c,Asset_Currency__c,Product__c,Status__c,Opportunity__c,Order_Type__c,Sales_Order__c,Shipping_Date__c,Purchase_Date__c,SLA__c,Support_End_Date__c,Support_Start_Date__c,assetNrdStartDate__c,assetNrdEndDate__c,Matched_Asset__c from Duplicate_Asset__c where Matched_Asset__c!=null';
    	batch_duplicate_rec bdr=new batch_duplicate_rec();
    	bdr.query=query;
    	Database.executebatch(bdr,1);  

    }
    
    static testMethod void myUnitTest() {
    	Test.StartTest();
		schedule_batch_duplicate_rec sh1 = new schedule_batch_duplicate_rec();
        String sch = '0 0 23 * * ?';
        system.schedule('Test Territory Check', sch, sh1);
		Test.stopTest();
		integer i=1;
        System.assertEquals(i,1);
    }
    
}