src/objects/Eval__c.object
<CustomObject>
    <description>This object is used to track Evals/Pilots that are in the field</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Evals</relationshipLabel>
        <relationshipName>Evals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Eval</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Eval Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/evaltriggertestclass.cls
@istest
public class evaltriggertestclass{
static testmethod void mytestmethod()
{
    account acc=new account(name='pri',CurrencyIsoCode='',type='distributor');
 insert acc;
    
    opportunity opp = new opportunity(name='test Opp',type='New Business',Sales_Area__c='NA West North',CurrencyIsoCode='',Reseller_Account__c=acc.id,StageName='prospect',closedate=date.today());
         insert opp;
    Eval__c ev=new Eval__c();
//ev.name='test';
ev.opportunity__c=opp.id;
insert ev;
}
}