src/objects/Expedite_Request__c.object
<CustomObject>
    <description>Custom Object for tracking Expedite Request Cases on Sales Orders.</description>
    <fields>
        <fullName>Approval_To_Overnight__c</fullName>
        <inlineHelpText>If you checked the box above to overnight, please copy and paste the approval to overnight.</inlineHelpText>
        <label>Approval To Overnight</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Overnight__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if you would like to overnight this Sales Order.</inlineHelpText>
        <label>Overnight</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This field is auto filled so no edits are needed.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Expedite Requests</relationshipLabel>
        <relationshipName>Expedite_Requests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Install_Date__c</fullName>
        <inlineHelpText>Date of customer install. Order Management will utilize this field in order to determine shipment date.</inlineHelpText>
        <label>Target Install Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Expedite Request</label>
    <nameField>
        <displayFormat>EXP-{000000}</displayFormat>
        <label>Expedite Request Case #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expedite Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Expedite_Request_Email__c.object
<CustomObject>
    <description>Custom Object for tracking Expedite Request Emails.</description>
    <fields>
        <fullName>Email_Body__c</fullName>
        <label>Email Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_Subject__c</fullName>
        <label>Email Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_To__c</fullName>
        <label>Email To:</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_cc__c</fullName>
        <label>Email CC:</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Expedite_Request__c</fullName>
        <label>Expedite Request</label>
        <referenceTo>Expedite_Request__c</referenceTo>
        <relationshipLabel>Expedite Request Emails</relationshipLabel>
        <relationshipName>Expedite_Request_Emails</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Expedite Request Email</label>
    <nameField>
        <displayFormat>ERE-{00000000}</displayFormat>
        <label>Expedite Request Email #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expedite Request Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Shipment_Date__c</fullName>
        <label>Actual Shipment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to OA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved by OA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by OA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order in Process</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Conversion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loaner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SoD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trunk Units</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prebuild</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Test_ExpediteEmailRequestEdit.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class Test_ExpediteEmailRequestEdit {

    static testMethod void myUnitTest() {
    	

        
    	
    	
		Sales_Order__c so= new Sales_Order__c();        
        so.Name='test mansa';
        so.Type__c='Internal';
        so.Status__c='Approved by OA';
        so.Actual_Shipment_Date__c=system.today();
        insert so;
        
                
         Expedite_Request__c exp=new Expedite_Request__c();
         exp.Approval_To_Overnight__c=' test mansa';
         exp.Overnight__c=true;
         exp.Sales_Order__c=so.id;
         exp.Target_Install_Date__c=system.today();
         insert exp;
         
         Expedite_Request_Email__c exemailinsert=new Expedite_Request_Email__c();
        exemailinsert.Email_Body__c='test';
        exemailinsert.Email_Subject__c='test subject';
        exemailinsert.Email_cc__c='test@mansa.com';
        exemailinsert.Email_To__c='test1@mansa.com';
        exemailinsert.Expedite_Request__c=exp.id;
        insert exemailinsert;
         
     	 PageReference pageRef = new PageReference('/apex/ExpediteEmailRequestEdit?retURL=%2F'+exp.Id);
		 Test.setCurrentPage(pageRef);         
         apexpages.currentPage().getParameters().put('EMId',exemailinsert.Id);    
                //  apexpages.currentPage().getParameters().put('retURL',exp.Id);       
            
         //apexpages.currentPage().getParameters().put('retURL',exp.Id);
         
         string email='test@gmail.com';
         string opname='name'; 
         ApexPages.StandardController sc = new ApexPages.StandardController(exp);
         ExpediteEmailRequestEdit expctrl= new ExpediteEmailRequestEdit(sc);
         expctrl.backtoexpedite();
         expctrl.cancel();
         expctrl.Reply();
         expctrl.replyall();
         expctrl.ReSend();
         expctrl.send();
         expctrl.sendwithattachment();
         ExpediteEmailRequestEdit.wrapexpemail wrap=new ExpediteEmailRequestEdit.wrapexpemail(opname,email);
         
                 
         
    }
    static testMethod void myUnitTest1() {
    	

        
    	
    	
		Sales_Order__c so= new Sales_Order__c();        
        so.Name='test mansa';
        so.Type__c='Internal';
        so.Status__c='Approved by OA';
        so.Actual_Shipment_Date__c=system.today();
        insert so;
        
                
         Expedite_Request__c exp=new Expedite_Request__c();
         exp.Approval_To_Overnight__c=' test mansa';
         exp.Overnight__c=true;
         exp.Sales_Order__c=so.id;
         exp.Target_Install_Date__c=system.today();
         insert exp;
         
         Expedite_Request_Email__c exemailinsert=new Expedite_Request_Email__c();
        exemailinsert.Email_Body__c='test';
        exemailinsert.Email_Subject__c='test subject';
        exemailinsert.Email_cc__c='test@mansa.com';
        exemailinsert.Email_To__c='test1@mansa.com';
        exemailinsert.Expedite_Request__c=exp.id;
        insert exemailinsert;
        Attachment attachment = new Attachment();

            attachment.Name = 'test';
            attachment.Body = Blob.valueOf('test hjjhjhj');
            attachment.ParentId = exemailinsert.Id;
            insert attachment;
             integer i=1;
        System.assertEquals(i,1);
        Attachment attachment1 = new Attachment();

            attachment1.Name = 'test';
            attachment1.Body = Blob.valueOf('test hjjhjhj');
            attachment1.ParentId = exemailinsert.Id;
            insert attachment1;
            
        Attachment attachment2 = new Attachment();

            attachment2.Name = 'test';
            attachment2.Body = Blob.valueOf('test hjjhjhj');
            attachment2.ParentId = exemailinsert.Id;
            insert attachment2;
            
        Attachment attachment4 = new Attachment();

            attachment4.Name = 'test';
            attachment4.Body = Blob.valueOf('test hjjhjhj');
            attachment4.ParentId = exemailinsert.Id;
            insert attachment4;
             
        
        
         
     	 PageReference pageRef = new PageReference('/apex/ExpediteEmailRequestEdit?retURL=%2F'+exp.Id);
		 Test.setCurrentPage(pageRef);         
         apexpages.currentPage().getParameters().put('EMId',exemailinsert.Id);    
                //  apexpages.currentPage().getParameters().put('retURL',exp.Id);       
            
         //apexpages.currentPage().getParameters().put('retURL',exp.Id);
         
          
         ApexPages.StandardController sc = new ApexPages.StandardController(exp);
         ExpediteEmailRequestEdit expctrl= new ExpediteEmailRequestEdit(sc);
         expctrl.checkattachment='False';
         expctrl.backtoexpedite();
         expctrl.cancel();
         expctrl.Reply();
         expctrl.replyall();
         expctrl.ReSend();
         expctrl.send();
         expctrl.sendwithattachment();
         expctrl.deleteatt();
         expctrl.deleteatt();
         expctrl.viewatt();
         expctrl.Editatt();
         
         
         
                 
         
    }
}