src/objects/Expedite_Request__c.object
<CustomObject>
    <description>Custom Object for tracking Expedite Request Cases on Sales Orders.</description>
    <fields>
        <fullName>Approval_To_Overnight__c</fullName>
        <inlineHelpText>If you checked the box above to overnight, please copy and paste the approval to overnight.</inlineHelpText>
        <label>Approval To Overnight</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Overnight__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if you would like to overnight this Sales Order.</inlineHelpText>
        <label>Overnight</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This field is auto filled so no edits are needed.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Expedite Requests</relationshipLabel>
        <relationshipName>Expedite_Requests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Install_Date__c</fullName>
        <inlineHelpText>Date of customer install. Order Management will utilize this field in order to determine shipment date.</inlineHelpText>
        <label>Target Install Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Expedite Request</label>
    <nameField>
        <displayFormat>EXP-{000000}</displayFormat>
        <label>Expedite Request Case #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expedite Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Shipment_Date__c</fullName>
        <label>Actual Shipment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to OA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved by OA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by OA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order in Process</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Conversion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loaner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SoD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trunk Units</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prebuild</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOLI-{000000}</displayFormat>
        <label>Sales Order Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_Salesorderlinectrl.cls
/**
 test class for controller Salesorderlinectrl
 */
@isTest
private class Test_Salesorderlinectrl {

    static testMethod void myUnitTest() {
    	Sales_Order__c so= new Sales_Order__c();
        
        so.Name='test mansa';
        so.Type__c='Internal';
        so.Status__c='Approved by OA';
        so.Actual_Shipment_Date__c=system.today();
        
        insert so;
        Sales_Order_Line__c soline=new Sales_Order_Line__c();
        
        soline.Sales_Order__c=so.id;
        insert soline;
        
         Expedite_Request__c exp=new Expedite_Request__c();
         exp.Approval_To_Overnight__c=' test mansa';
         exp.Overnight__c=true;
         exp.Sales_Order__c=so.id;
         exp.Target_Install_Date__c=system.today();
         insert exp;
         
        apexpages.currentPage().getParameters().put('Id',exp.Id);
        
        salesorderlinectrl test= new salesorderlinectrl();
        ApexPages.StandardController sc = new ApexPages.StandardController(exp);
        salesorderlinectrl salelines=new salesorderlinectrl(sc);
        salelines.salesorderline();
       
        
    	
    }
}