src/objects/Expedite_Request__c.object
<CustomObject>
    <description>Custom Object for tracking Expedite Request Cases on Sales Orders.</description>
    <fields>
        <fullName>Approval_To_Overnight__c</fullName>
        <inlineHelpText>If you checked the box above to overnight, please copy and paste the approval to overnight.</inlineHelpText>
        <label>Approval To Overnight</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Current_Ship_Date__c</fullName>
        <formula>Sales_Order__r.Shipment_Date__c</formula>
        <inlineHelpText>This field is auto-populated. No further information needed.</inlineHelpText>
        <label>Current Ship Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expedite_Status__c</fullName>
        <label>Expedite Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Sched_Ship_Date_Update__c</fullName>
        <label>Last Sched Ship Date Update</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opp_Team_10__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 10</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests45H3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_6__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 6</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_7__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 7</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_8__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 8</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_9__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 9</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Overnight__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if you would like to overnight this Sales Order.</inlineHelpText>
        <label>Overnight</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reason_For_Expedite__c</fullName>
        <inlineHelpText>Please explain why you are requesting this expedite.</inlineHelpText>
        <label>Reason For Expedite</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SO_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SO Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This field is auto filled so no edits are needed.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Expedite Requests</relationshipLabel>
        <relationshipName>Expedite_Requests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_To_Address__c</fullName>
        <formula>Sales_Order__r.Ship_To_Address_1__c  &amp;  BR()  &amp;  Sales_Order__r.Ship_To_Address_2__c  &amp;  BR()  &amp;  Sales_Order__r.Ship_To_City__c  &amp; &quot;,&quot;  &amp;  Sales_Order__r.Ship_to_State__c  &amp;  Sales_Order__r.Ship_To_Zip_Postal_Code__c  &amp;  BR()  &amp;  Sales_Order__r.Ship_To_Country__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field is auto-populated. No further information needed.</inlineHelpText>
        <label>Ship To Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Customer__c</fullName>
        <formula>Sales_Order__r.Ship_To_Company__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field is auto-populated. No further information needed.</inlineHelpText>
        <label>Ship to Customer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Install_Date__c</fullName>
        <inlineHelpText>Date of customer install. Order Management will utilize this field in order to determine shipment date.</inlineHelpText>
        <label>Target Install Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Expedite Request</label>
    <nameField>
        <displayFormat>EXP-{000000}</displayFormat>
        <label>Expedite Request Case #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expedite Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Shipment_Date__c</fullName>
        <label>Actual Shipment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to OA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved by OA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by OA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order in Process</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Conversion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loaner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SoD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trunk Units</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prebuild</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Test_BatchEmailNotificationUsers.cls
/**
 
 */
@isTest
private class Test_BatchEmailNotificationUsers {

    static testMethod void myUnitTest() {
    	Sales_Order__c so= new Sales_Order__c();
        
        so.Name='test mansa';
        so.Type__c='Internal';
        so.Status__c='Approved by OA';
        so.Actual_Shipment_Date__c=system.today();
        
        insert so;
        list<Expedite_Request__c> explist=new list<Expedite_Request__c>();
         Expedite_Request__c exp=new Expedite_Request__c();
         exp.Approval_To_Overnight__c='test';
         exp.Overnight__c=true;
         exp.Sales_Order__c=so.id;
         exp.Last_Sched_Ship_Date_Update__c=null;
         exp.Expedite_Status__c='Open';
         exp.Target_Install_Date__c=system.today();
         insert exp;
         explist.add(exp);
         
          Test.startTest();
        BatchEmailNotificationUsers bse=new BatchEmailNotificationUsers();
                bse.query='Select id,OwnerId,SO_Owner__c,name,Sales_Order__r.name,Target_Install_Date__c,Expedite_Status__c,Approval_To_Overnight__c, Ship_to_Customer__c, Ship_To_Address__c, Sales_Order__c, Reason_For_Expedite__c,Overnight__c, Opp_Team_9__c, Opp_Team_8__c, Opp_Team_7__c, Opp_Team_6__c, Opp_Team_5__c, Opp_Team_4__c, Opp_Team_3__c, Opp_Team_2__c, Opp_Team_1__c,Opp_Team_10__c, Current_Ship_Date__c ,Last_Sched_Ship_Date_Update__c from Expedite_Request__c where Last_Sched_Ship_Date_Update__c=null and Expedite_Status__c=\'Open\'';
        
        //bse.salesOrderIds=idss;
        bse.execute(null,explist);
        ID batchprocessid = Database.executeBatch(bse);
        
        Test.stopTest();
        integer i=1;
        System.assertEquals(i,1);
         

    }
}