src/objects/Expedite_Request__c.object
<CustomObject>
    <description>Custom Object for tracking Expedite Request Cases on Sales Orders.</description>
    <label>Expedite Request</label>
    <nameField>
        <displayFormat>EXP-{000000}</displayFormat>
        <label>Expedite Request Case #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expedite Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Expedite_Request_Email__c.object
<CustomObject>
    <description>Custom Object for tracking Expedite Request Emails.</description>
    <fields>
        <fullName>Email_Body__c</fullName>
        <label>Email Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_From__c</fullName>
        <label>Email From:</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_Subject__c</fullName>
        <label>Email Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_cc__c</fullName>
        <label>Email CC:</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Expedite_Request__c</fullName>
        <label>Expedite Request</label>
        <referenceTo>Expedite_Request__c</referenceTo>
        <relationshipLabel>Expedite Request Emails</relationshipLabel>
        <relationshipName>Expedite_Request_Emails</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Inbound_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inbound Indicator</label>
        <type>Checkbox</type>
    </fields>
    <label>Expedite Request Email</label>
    <nameField>
        <displayFormat>ERE-{00000000}</displayFormat>
        <label>Expedite Request Email #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expedite Request Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ExpediteRequestEmailService.cls
/**
 * Email services are automated processes that use Apex classes
 * to process the contents, headers, and attachments of inbound
 * email.
 */
global class ExpediteRequestEmailService implements Messaging.InboundEmailHandler {

    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {
        Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();
        
        
         
    String myPlainText= '';
    // Add the email plain text into the local variable 
    string plainsub=email.subject;
    list<string> divsub=new list<string>();
	divsub=plainsub.split('ref:');
    string ccadress=' ';
    list<string> cclist=new list<string>();
    email.ccAddresses=new list<string>();
    cclist=email.ccAddresses;
    if(cclist.size()>0)
    {
    for(string s:email.ccAddresses)
    {
    	ccadress+=s+';';
    }
    ccadress=ccadress.subString(0,ccadress.lastIndexOf(';'));
    system.debug('ccadress');
    }
    else
    ccadress=' ';
    
    
    
    string expname=' ';
    
    expname=divsub[1];
    system.debug('expname---------'+expname);
    expname=expname.subString(0,expname.lastIndexOf(']'));
    Expedite_Request__c expre=new Expedite_Request__c();
  //  Expedite_Request_Email__c exemail=[select id,name,Expedite_Request__c from Expedite_Request_Email__c where name=:expname];
    expre=[select id,name from Expedite_Request__c where name=:expname];
    myPlainText = email.plainTextBody;
    Expedite_Request_Email__c  expemail= new Expedite_Request_Email__c();
    expemail.Email_Body__c=email.plainTextBody;
    
    expemail.Email_cc__c=ccadress;
    expemail.Email_From__c=email.fromAddress;
    expemail.Expedite_Request__c=expre.id;
    expemail.Inbound_Indicator__c=true;
    expemail.Email_Subject__c=email.subject;
    insert expemail; 
    List<Attachment> attList = new List<Attachment>();
    // This will extract all blob attachments from email
     if (email.textAttachments != null) {
     	system.debug('text--------------');
            for(Messaging.Inboundemail.TextAttachment tAttachment : email.textAttachments) {
            Attachment attachment = new Attachment();

            attachment.Name = tAttachment.fileName;
            attachment.Body = Blob.valueOf(tAttachment.body);
            attachment.ParentId = expemail.Id;
            attList .add(attachment);
            }
            }
    
    if(email.binaryAttachments!=null)
    {
    	
    
    for (Messaging.Inboundemail.BinaryAttachment file : email.binaryAttachments) 
    {
      Attachment attachment = new Attachment();
      attachment.Name = file .fileName;
      attachment.Body = file .body;
      // some hardcoded or id extracted from email reference
      attachment.ParentId = expemail.ID;
      attList .add(attachment);
   }
    }
    
   if(attList .size()>0)
   {
     insert attList;
   }

        return result;
    }
}