src/objects/Expedite_Request__c.object
<CustomObject>
    <description>Custom Object for tracking Expedite Request Cases on Sales Orders.</description>
    <fields>
        <fullName>Approval_To_Overnight__c</fullName>
        <inlineHelpText>If you checked the box above to overnight, please copy and paste the approval to overnight.</inlineHelpText>
        <label>Approval To Overnight</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Current_Ship_Date__c</fullName>
        <formula>Sales_Order__r.Shipment_Date__c</formula>
        <inlineHelpText>This field is auto-populated. No further information needed.</inlineHelpText>
        <label>Current Ship Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Sched_Ship_Date_Update__c</fullName>
        <label>Last Sched Ship Date Update</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opp_Team_10__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 10</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests45H3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_6__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 6</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_7__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 7</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_8__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 8</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_9__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 9</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_For_Expedite__c</fullName>
        <inlineHelpText>Please explain why you are requesting this expedite.</inlineHelpText>
        <label>Reason For Expedite</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SO_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SO Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This field is auto filled so no edits are needed.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Expedite Requests</relationshipLabel>
        <relationshipName>Expedite_Requests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_To_Address__c</fullName>
        <formula>Sales_Order__r.Ship_To_Address_1__c  &amp;  BR()  &amp;  Sales_Order__r.Ship_To_Address_2__c  &amp;  BR()  &amp;  Sales_Order__r.Ship_To_City__c  &amp; &quot;,&quot;  &amp;  Sales_Order__r.Ship_to_State__c  &amp;  Sales_Order__r.Ship_To_Zip_Postal_Code__c  &amp;  BR()  &amp;  Sales_Order__r.Ship_To_Country__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field is auto-populated. No further information needed.</inlineHelpText>
        <label>Ship To Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Customer__c</fullName>
        <formula>Sales_Order__r.Ship_To_Company__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field is auto-populated. No further information needed.</inlineHelpText>
        <label>Ship to Customer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Install_Date__c</fullName>
        <inlineHelpText>Date of customer install. Order Management will utilize this field in order to determine shipment date.</inlineHelpText>
        <label>Target Install Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Expedite Request</label>
    <nameField>
        <displayFormat>EXP-{000000}</displayFormat>
        <label>Expedite Request Case #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expedite Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Sales_Order__c.object
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BatchEmailNotificationUsers.cls
global with sharing class BatchEmailNotificationUsers implements Database.Stateful,Database.Batchable<sObject>{
    global string query;
    global datetime dtbatch; 
    
    
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator(query);  
    }
    global void execute(Database.BatchableContext BC,  list<Expedite_request__c> scope)  
    {                   
        /*decimal decHours=0.00;
        system.debug('dtbatch------------'+dtbatch);
        
                system.debug('la time------------'+scope[0].Name);
        if(dtbatch == null)
        {
            decHours=(scope[0].Last_Act_Ship_Date_Update__c.getTime())/1000/60;
        }
        else
        {
        decHours = ((dtbatch.getTime())/1000/60) - ((scope[0].Last_Act_Ship_Date_Update__c.getTime())/1000/60);
        }
        system.debug('dechours---------'+decHours);
    if(decHours >1440)
    {    
    */  
        list<string> emailList=new list<string>();
        list<string> ccaddress=new list<string>();
        list<user> uslist=[select id,email,name from user where id=:scope[0].SO_Owner__c or id=:scope[0].Opp_Team_1__c or id=:scope[0].Opp_Team_2__c or id=:scope[0].Opp_Team_3__c 
                       or id=:scope[0].Opp_Team_4__c or id=:scope[0].Opp_Team_5__c or id=:scope[0].Opp_Team_6__c or id=:scope[0].Opp_Team_7__c or id=:scope[0].Opp_Team_8__c 
                       or id=:scope[0].Opp_Team_9__c  or id=:scope[0].Opp_Team_10__c or id=:scope[0].OwnerId ];
                       
                       system.debug('userlist-----------------'+uslist);
        
        for(user u: uslist)
        {
            emailList.add(u.email);
        }
        if(scope[0].Approval_To_Overnight__c==null)
        {
            scope[0].Approval_To_Overnight__c=' ';
        }
        if(scope[0].Reason_For_Expedite__c==null)
        {
            scope[0].Reason_For_Expedite__c=' ';
        }
        ccaddress.add('expedites.orders@nimblestorage.com');
         
        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(emaillist);
        
        mail.setCcAddresses(ccaddress);
        String subject='The Expedite Request for Sales Order '+scope[0].Sales_order__r.Name +'has not been updated.';
        string body='<html><body><p>The following Expedite Request for the noted Sales Order has not been updated with a new Shipping Date.'+' '+
                    'Please click the link below to review</p><p>&nbsp;</p>';
                    
        body+= '<p> Expedite Request Case #:'+'<a target="_blank" href="'+URL.getSalesforceBaseUrl().toExternalForm()+'/'+scope[0].Id+'">'+  scope[0].name+'</p></a>';
        body+= '<p> Sales Order:'+'<a target="_blank" href="'+URL.getSalesforceBaseUrl().toExternalForm()+'/'+scope[0].Sales_Order__c+'">'+  scope[0].Sales_Order__r.name+'</p></a>';        
        body+= '<p> Ship To Customer:'+  scope[0].Ship_to_Customer__c+'</p>';       
        body+= '<p> Ship To Address:'+  scope[0].Ship_To_Address__c+'</p>';     
        body+= '<p> Current Ship Date:'+  scope[0].Current_Ship_Date__c+'</p>';     
        body+= '<p> Target Install Date:'+  scope[0].Target_Install_Date__c+'</p>';
        body+= '<p> Last Actual Ship Date Update:'+  scope[0].Last_Sched_Ship_Date_Update__c+'</p>';        
        body+= '<p> Overnight:'+  scope[0].Approval_To_Overnight__c+'</p>';     
        body+= '<p> Approval to Overnight:'+  scope[0].Approval_To_Overnight__c+'</p>';     
        body+= '<p> Reason for Expedite:'+  scope[0].Reason_For_Expedite__c+'</p></html></body>';
        
        mail.setHtmlBody(body); 
        mail.setSubject(subject);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail }); 
        
            
   // }
    }
    
    global void finish(Database.BatchableContext BC)
    {
        
    } 
}