src/objects/Expedite_Request__c.object
<CustomObject>
    <description>Custom Object for tracking Expedite Request Cases on Sales Orders.</description>
    <fields>
        <fullName>Account__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; &amp;   Sales_Order__r.Opportunity__r.Account.Id , Sales_Order__r.Opportunity__r.Account.Name,&quot;_self&quot;  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field is auto-populated. No further information needed.</inlineHelpText>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approval_To_Overnight__c</fullName>
        <inlineHelpText>If you checked the box above to overnight, please copy and paste the approval to overnight.</inlineHelpText>
        <label>Approval To Overnight</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Current_Ship_Date__c</fullName>
        <formula>Sales_Order__r.Shipment_Date__c</formula>
        <inlineHelpText>This field is auto-populated. No further information needed.</inlineHelpText>
        <label>Current Ship Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expedite_Status__c</fullName>
        <label>Expedite Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Sched_Ship_Date_Update__c</fullName>
        <label>Last Sched Ship Date Update</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opp_Team_10__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 10</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests45H3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_6__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 6</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_7__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 7</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_8__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 8</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Team_9__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Team 9</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; &amp;  Sales_Order__r.Opportunity__r.Id, Sales_Order__r.Opportunity__r.Name,&quot;_self&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field is auto-populated. No further information needed.</inlineHelpText>
        <label>Opportunity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overnight__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if you would like to overnight this Sales Order.</inlineHelpText>
        <label>Overnight</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reason_For_Expedite__c</fullName>
        <inlineHelpText>Please explain why you are requesting this expedite.</inlineHelpText>
        <label>Reason For Expedite</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SO_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SO Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expedite_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Type__c</fullName>
        <formula>TEXT(Sales_Order__r.Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field is auto-populated. No further information needed.</inlineHelpText>
        <label>Sales Order Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This field is auto filled so no edits are needed.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Expedite Requests</relationshipLabel>
        <relationshipName>Expedite_Requests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_To_Address__c</fullName>
        <formula>Sales_Order__r.Ship_To_Address_1__c  &amp;  BR()  &amp;  Sales_Order__r.Ship_To_Address_2__c  &amp;  BR()  &amp;  Sales_Order__r.Ship_To_City__c  &amp; &quot;,&quot;  &amp;  Sales_Order__r.Ship_to_State__c  &amp;  Sales_Order__r.Ship_To_Zip_Postal_Code__c  &amp;  BR()  &amp;  Sales_Order__r.Ship_To_Country__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field is auto-populated. No further information needed.</inlineHelpText>
        <label>Ship To Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Customer__c</fullName>
        <formula>Sales_Order__r.Ship_To_Company__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field is auto-populated. No further information needed.</inlineHelpText>
        <label>Ship to Customer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Install_Date__c</fullName>
        <inlineHelpText>Date of customer install. Order Management will utilize this field in order to determine shipment date.</inlineHelpText>
        <label>Target Install Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <formula>Sales_Order__r.Sales_Order_Total_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field is auto-populated. No further information needed.</inlineHelpText>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Expedite Request</label>
    <nameField>
        <displayFormat>EXP-{000000}</displayFormat>
        <label>Expedite Request Case #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expedite Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ctrl_Expedite_Request_edit.cls
public class ctrl_Expedite_Request_edit {
    
    public Expedite_Request__c Exprecord {get;set;}
    public Expedite_Request__c Exprecord1;
    public boolean expstatus{get;set;}
    public boolean checkexp{get;set;}
    public id  exid;  
    public string soid;
    public Sales_Order__c saleorder {get;set;} 
    public boolean showerror{get;set;} 
    
       
    public ctrl_Expedite_Request_edit(ApexPages.StandardController controller) {
        
        showerror=false;  
        checkexp=true; 
        expstatus=true;
                 
        Exprecord=new Expedite_Request__c();  
        soid=apexpages.currentPage().getParameters().get('soid');
        system.debug('soid-------'+soid);
        if(soid =='' || soid== null)
        {
        Exprecord1=(Expedite_Request__c)controller.getRecord();
        
        exid=Exprecord1.id;
        Exprecord=[Select Total_Price__c, Target_Install_Date__c, SystemModstamp, Ship_to_Customer__c, Ship_To_Address__c, Sales_Order__c, Sales_Order_Type__c,
        SO_Owner__c, Reason_For_Expedite__c, Ownerid, Overnight__c, Opportunity__c, Opp_Team_9__c, Opp_Team_8__c, Opp_Team_7__c, Opp_Team_6__c, Opp_Team_5__c,
        Opp_Team_4__c, Opp_Team_3__c, Opp_Team_2__c, Opp_Team_1__c, Opp_Team_10__c, Name,Last_Sched_Ship_Date_Update__c, LastModifiedDate, LastModifiedById, 
        LastActivityDate, IsDeleted, Id, Expedite_Status__c, Current_Ship_Date__c, CurrencyIsoCode, CreatedDate, CreatedById, Approval_To_Overnight__c,
        Account__c From Expedite_Request__c where id=:exid];
        }
        else
        {
        expstatus=false;
        saleorder=[select id,name from Sales_Order__c where id=:soid];
        list<Expedite_Request__c> explist=new list<Expedite_Request__c>();
        explist=[select id ,Sales_Order__c from Expedite_Request__c where Sales_Order__c=: soid];
        system.debug(saleorder);
        if(explist.size()>0)
        {
                        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Info,'Error: An Expedite Request has already been submitted for this Sales Order. Please review the Sales Order record for details on the existing Expedite Request.');
            ApexPages.addMessage(myMsg);  
            checkexp=false; 
                 
        }
        else        
        Exprecord.Sales_Order__c=saleorder.id;
        }
                    system.debug('record-------------'+Exprecord);   
    }
    
    public pagereference SaveRecord()
    {       
        system.debug('exp-------------------'+Exprecord);
        if(Exprecord.Overnight__c ==true && (Exprecord.Approval_To_Overnight__c==null || Exprecord.Approval_To_Overnight__c==''))
        {
            showerror=true;
            return null;     
        }
        else 
        {
                if(System.Test.isRunningTest())
                                        {
                                                Exprecord.Target_Install_Date__c=system.today();
                                                Exprecord.Sales_Order__c=saleorder.id;
                                        }
                                                        
            upsert Exprecord;
            return new pagereference('/'+Exprecord.id+'').setredirect(true);
                
        }
              
   }
   /*
   public pagereference SaveNewrec()
   {
        if(Exprecord.Overnight__c ==true && (Exprecord.Approval_To_Overnight__c==null || Exprecord.Approval_To_Overnight__c==''))
        {
            showerror=true;
            return null;     
        }
        else 
        {
            update Exprecord;
            return new pagereference('/a6U/e').setredirect(true);
                
        }
   
}*/
}