src/objects/Inbox__c.object
<CustomObject>
    <fields>
        <fullName>Reseller_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reseller Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inboxes (Reseller Account)</relationshipLabel>
        <relationshipName>Inboxes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reseller_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reseller Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Inboxes</relationshipLabel>
        <relationshipName>Inboxes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inbox</label>
    <nameField>
        <label>Reseller Inbox Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inboxes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Reseller_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Reseller_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reseller Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reseller Contacts (Reseller Account)</relationshipLabel>
        <relationshipName>Reseller_Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reseller Contact</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Reseller Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reseller Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/InboxAndResellerConUpdateTest.cls
@isTest(seeAllData = true)
public class InboxAndResellerConUpdateTest{
   public static testMethod void main(){
       ID ProfileID = [ Select id from Profile where name = 'Support: System Administrator'].id;
         User usr = new User(email='test-user@example1.com',profileid = ProfileID, 
                      UserName='test-user@email.com',alias='tuser1',CommunityNickName='tuser',TimeZoneSidKey='America/New_York', 
                      LocaleSidKey='en_US',EmailEncodingKey='ISO-8859-1',LanguageLocaleKey='en_US', 
                      FirstName = 'Test',LastName = 'UserTest' );
         insert usr;
         System.runAs(usr) {
            ID accRecordType = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Support Provider'].Id;
            RecordType rt2 = [select id,Name from RecordType where SobjectType='Account' and Name='Channel' Limit 1];
            Account supAcct = new Account(Name = 'TestSuppProvider', Type = 'Support Provider', Email__c = 'supemail@test.com', RecordTypeId = accRecordType);
            insert supAcct; //create support provider account
            Account supAcct2 = new Account(Name = 'TestSuppProvider', Type = 'Support Provider', Email__c = 'supemail@test.com', RecordTypeId = accRecordType);
            insert supAcct2; //create support provider account
            Account resAcct = new Account(Name = 'TestResAcct', Type = 'Reseller',RecordTypeId = rt2.id,Support_Provider__c = supAcct.id);
            insert resAcct; //create reseller account
            Inbox__c inbx = new Inbox__c(Reseller_Account__c = resAcct.Id);
            insert inbx;
            Reseller_Contact__c rc = new Reseller_Contact__c(Reseller_Account__c = resAcct.Id);
            insert rc; //create reseller contact 
            resAcct.Support_Provider__c = supAcct2.id;
            update  resAcct;
        }    
   }
}