src/objects/Outstanding_Recommendation__c.object
<CustomObject>
    <description>Recommendations and fixes made by Support/Engineering are logged in this object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Outstanding Recommendations</relationshipLabel>
        <relationshipName>Outstanding_Recommendations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Outstanding Recommendations</relationshipLabel>
        <relationshipName>Outstanding_Recommendations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Outstanding Recommendations</relationshipLabel>
        <relationshipName>Outstanding_Recommendations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Outstanding Recommendations</relationshipLabel>
        <relationshipName>Outstanding_Recommendations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recommended_Action__c</fullName>
        <label>Recommended Action</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Outstanding Recommendation</label>
    <nameField>
        <displayFormat>Rec-{00000000}</displayFormat>
        <label>Rec Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outstanding Recommendations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CaseRecommendation.cls
global with sharing class CaseRecommendation{
private List<Outstanding_Recommendation__c> recz;
public Case cse{get;set;}
public String cseAccountID = null;

public integer list_size=30; //sets the page size or number of rows
public integer total_size; //used to show user the total size of the list

    public CaseRecommendation(ApexPages.StandardController controller) {
        this.cse=(Case)controller.getRecord();
        
        if(cse.id != null)
        { 
            Case cas = [Select id, Account.id FROM Case where id =:cse.id];
            
            if(cas.Account!=null)
            {
                this.cseAccountID = cas.Account.Id;
                executeCount();
            }
        }
    }
    
    public void executeCount()
    {
            this.total_size = [select count() from Outstanding_Recommendation__c where Account__r.Id =:cseAccountID];
    }
    
     public List<Outstanding_Recommendation__c> getRecz()
    {
        if(cseAccountID == null)
        return null;
        recz = [Select id, Name,Status__c,Recommended_Action__c, Account__r.Name,Case__r.CaseNumber,Asset__r.Name,Contact__r.Name from Outstanding_Recommendation__c where Account__r.Id =:cseAccountID ORDER BY Case__r.CaseNumber limit:list_size];
        return recz;
    }
    
    public PageReference showMore() { 
       list_size = list_size + 10;
       return null;
   }
   
   public String getFooter()
   {
     
     if(total_size > list_size)
     {
        return 'Showing Record(s) ' + list_size + ' out of ' + total_size;
     }
     else if(total_size <= list_size && total_size != 0)
     {
        return 'Showing Record(s) ' + total_size+ ' out of ' + total_size;
     }
     else
     {
        return 'No Records to Display';
     }
   }
   
   public Boolean getdisableValue()
   {
     if(total_size <= list_size || total_size ==0)
     {
        return true;
     }
     else
     {
        return false;
     }
   }
   
}