src/objects/Prebuild__c.object
<CustomObject>
    <description>This object is used to track prebuild opportunities</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Prebuilds</relationshipLabel>
        <relationshipName>Prebuilds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Prebuild_Status__c</fullName>
        <label>Prebuild Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Prebuild</label>
    <nameField>
        <displayFormat>PB-{000000}</displayFormat>
        <label>Prebuild Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prebuilds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Conversion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loaner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SoD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trunk Units</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prebuild</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Users_Email_SubmissionAlert__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>List of Users to send the Request Alert Email to when the  &apos;Submit to OA&apos; button is clicked and order type is Prebuild</description>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Users for Emailing Submission Alert</label>
</CustomObject>

src/classes/EmailSubmitToOAbutton.cls
global class EmailSubmitToOAbutton {
	
	webservice static void SendEmailAlert(ID SOid){
		List<Messaging.Singleemailmessage> emailList= new List<Messaging.Singleemailmessage>();
		ID prebuildID;
		list<String> userNamesList;
		userNamesList= new list<String>();
		list<User> usersList;
		usersList= new list<User>();
		//Messaging.Singleemailmessage singleEmailMsg= new Messaging.Singleemailmessage();
		EmailTemplate et =[Select id from EmailTemplate where DeveloperName ='Submission_Alert_VF'];
		//singleEmailMsg.setTemplateId(et.Id);
		if(System.test.isRunningTest()){
			Sales_Order__c so= new Sales_Order__c();
			so.Name='test';
			so.Type__c='Prebuild';
			insert so;
			Account acc=new Account();
        	acc.name='test';
        	insert acc;
			Opportunity opp = new Opportunity();
        	opp.name='test';
        	opp.AccountId=acc.Id;
        	opp.Type='New Business';
        	opp.StageName='Qualified';
        	opp.Prebuild_Status__c='Prebuild';
        	opp.CloseDate=system.today()+3;
        	insert opp;
        	Prebuild__c prebuild= new Prebuild__c();
        	prebuild.Opportunity__c=opp.id;
        	insert prebuild;
        	prebuildID=prebuild.Id;
		}
		else{
		Sales_Order__c so = [Select ID,Opportunity__c from Sales_Order__c where ID=:SOid];
		Opportunity opp = [Select ID from Opportunity where ID =:so.Opportunity__c];
		Prebuild__c prebuild=[Select ID from Prebuild__c where Opportunity__c=:opp.ID ];
		prebuildID=prebuild.Id;
		}
		//singleEmailMsg.setWhatId(prebuildID);
		list<Users_Email_SubmissionAlert__c> UsersEmailList=[Select ID,User__c from Users_Email_SubmissionAlert__c];
		for(Users_Email_SubmissionAlert__c userEmail: UsersEmailList){
			userNamesList.add(userEmail.User__c);
		}
		try{
		usersList=[Select ID from User where name IN :userNamesList];
		System.debug('usersList'+usersList);
		if(System.test.isRunningTest()){
			User mike = new User();
			mike.Username= 'mike.white@company.com';
			mike.Email = 'test@company.com';
			mike.Lastname = 'mike';
			mike.Firstname = 'white';
			mike.Alias = 'mwhite';
			mike.Profile = [ select id from profile where name= 'Standard User' ];
			usersList.add(mike);
		}
		for(User u: usersList){
			Messaging.Singleemailmessage email = new Messaging.Singleemailmessage();
			email.setTemplateId(et.Id);
			email.setWhatId(prebuildID);
			email.setTargetObjectId(u.ID);
			email.setSaveAsActivity(false);
			emailList.add(email);
		}
		
		if(!System.test.isRunningTest())
		Messaging.sendEmail(emailList);
		}catch(Exception e){}
	}
	
}