src/objects/Prebuild__c.object
<CustomObject>
    <description>This object is used to track prebuild opportunities</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Prebuilds</relationshipLabel>
        <relationshipName>Prebuilds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Prebuild</label>
    <nameField>
        <displayFormat>PB-{000000}</displayFormat>
        <label>Prebuild Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prebuilds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Conversion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loaner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SoD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trunk Units</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prebuild</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>BOM_Line_Number__c</fullName>
        <label>BOM Line Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Package_Product_Code__c</fullName>
        <label>Package Product Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sale_Price__c</fullName>
        <label>Sale Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOLI-{000000}</displayFormat>
        <label>Sales Order Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SalesOrderAndSOlinesTemplate.cls
public with sharing class SalesOrderAndSOlinesTemplate {

public ID oppID{get;set;}
public ID SOid;

public Sales_Order__c getSO(){
    if(System.test.isRunningTest()){
        Opportunity opp=new Opportunity();
        opp.Name='test';
        opp.StageName='0 - DisQualified';
        opp.CloseDate=System.today();
        opp.Type='New Business';
        insert opp;
        Prebuild__c prebuild=new Prebuild__c();
        prebuild.Opportunity__c=opp.Id;
        insert prebuild;
        Sales_Order__c sotest=new Sales_Order__c();
        sotest.Name='test';
        sotest.CurrencyIsoCode='AUD';
        sotest.Type__c='Prebuild';
        sotest.Opportunity__c=opp.Id;
        insert sotest;
        Sales_Order_Line__c soltest=new Sales_Order_Line__c();
        soltest.Sales_Order__c=sotest.Id;
        soltest.CurrencyIsoCode='AUD';
        oppID=opp.ID;
    }
    Sales_Order__c SO;
    try{
    SO=[Select s.Type__c, s.Owner.Name, s.Name From Sales_Order__c s where s.Opportunity__c=:oppID and s.Type__c='Prebuild' limit 1];
    SOid=SO.Id;
    }catch(Exception e){} 
    return SO;
     
}
public list<Sales_Order_Line__c> getSOlines(){
    list<Sales_Order_Line__c> SOlinesList;
    Sales_Order__c SO;
    try{
    SO=[Select s.Type__c, s.Owner.Name, s.Name From Sales_Order__c s where s.Opportunity__c=:oppID and s.Type__c='Prebuild' limit 1];
    SOid=SO.Id;
    }catch(Exception e){}
    try{
    SOlinesList=[Select s.Sale_Price__c, s.Quantity__c, s.Product__r.Name, s.Package_Product_Code__c, s.Name, s.BOM_Line_Number__c From Sales_Order_Line__c s where s.Sales_Order__c=:SOid];
    }catch(Exception e){}
    return SOlinesList;
}
}