src/objects/Recommendation__c.object
<CustomObject>
    <description>This is object is child object to Lead. The records will have different categories to (CPU/Cache/Controller) types when a customer hits the limit.</description>
    <fields>
        <fullName>Asset_SN__c</fullName>
        <label>Asset SN</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Recommendations</relationshipLabel>
        <relationshipName>Recommendations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Infosight Upgrade Recommendations</relationshipLabel>
        <relationshipName>Recommendations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recommendation_Text__c</fullName>
        <inlineHelpText>This field gives a textual description of the recommendation.</inlineHelpText>
        <label>Recommendation Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The recommendation status is either “Active” or “Inactive”. All recommendations are generated in the active state and are only moved into the inactive state manually.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Recommendation</label>
    <nameField>
        <displayFormat>RC-{0000}</displayFormat>
        <label>Recommendation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommendations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestRecommendationTrigger.cls
@isTest
public class TestRecommendationTrigger
{

    static testMethod void testLeadAssignmentonRec()
    {
        Account acc = new Account(Name='Test Acc');
        insert acc;
        Lead l = new Lead(FirstName='Test',LastName='Lead',Company='Test Company',Status='Closed');
        insert l;
        Asset asst = new Asset(Name='Test Asset1', SerialNumber='SN123', AccountId=acc.Id);
        insert asst;
        Asset asst1 = new Asset(Name='Test Asset2',SerialNumber='SN345',Lead__c=l.Id,AccountId=acc.Id);
        insert asst1;
        Recommendation__c rec1 = new Recommendation__c(Asset__c=asst.Id, Asset_SN__c='SN123');
        Recommendation__c rec2 = new Recommendation__c(Asset__c=asst1.Id,Asset_SN__c='SN345');
        Recommendation__c rec3 = new Recommendation__c(Asset__c=asst1.Id,Asset_SN__c='SN678',Status__c='Inactive');
        List<Recommendation__c> recList = new List<Recommendation__c>();
        recList.add(rec1);
        recList.add(rec2);
        recList.add(rec3);
        insert recList;
        Set<Id> recIds = new Set<Id>();
        recIds.add(rec1.Id);
        recIds.add(rec2.Id);
        recIds.add(rec3.Id);
        Map<Id,Recommendation__c> recMap = new Map<Id,Recommendation__c>([select Id, Lead__c,Lead__r.Status,Status__c from Recommendation__c where Id in :recIds]);
        Recommendation__c rec1_v = recMap.get(rec1.Id);
        Recommendation__c rec2_v = recMap.get(rec2.Id);
        System.assertNotEquals(rec1_v.Lead__c,null);
        System.assertEquals(rec2_v.Lead__r.Status,'Open');
        rec2.Status__c = 'Inactive';
        rec2.Recommendation_Text__c = 'Rec text';
        update rec2;
        Lead l_v = [select Id,Lead_Text__c from Lead where Id =: l.Id];
        System.assertEquals(rec2.Recommendation_Text__c,l_v.Lead_Text__c);
        
    }
}