src/objects/Reseller_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is to store the Asset S.NO/Asset Name on the Reseller Contact object.</description>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Reseller Contacts</relationshipLabel>
        <relationshipName>Reseller_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Res_Email__c</fullName>
        <formula>ResellerContact__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reseller Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reseller_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reseller Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reseller Contacts (Reseller Account)</relationshipLabel>
        <relationshipName>Reseller_Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>resellerCustomerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reseller Contacts</relationshipLabel>
        <relationshipName>Reseller_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reseller Contact</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Reseller Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reseller Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/GetCustomerAccountService.cls
@RestResource(urlMapping='/customeracct/*')
global class GetCustomerAccountService
{
    @HttpGet
    global static AccountResponse getCustomerAccounts()
    { 
        AccountResponse ar = new AccountResponse();
        try
        {
            Restrequest req = RestContext.request;
            if(Test.isRunningTest()) {
            req = new Restrequest();
            req.addParameter('email',TestResellerCS.EMAIL_PARAM);
            }
            Map<String,String> params = req.params;
            if(params != null)
            {
               
                String resEmail = params.get('email');           
                List<Reseller_Contact__c> rcList = [SELECT Id, Status__c, resellerCustomerAccount__r.Name, Reseller_Account__r.Name, Reseller_Account__c, resellerCustomerAccount__c, Res_Email__c, Asset__r.SerialNumber from Reseller_Contact__c WHERE Res_Email__c = :resEmail]; 
                List<AccountData> customers = new List<AccountData>();             
                for(Reseller_Contact__c rc : rcList)
                {
                   AccountData ad = new AccountData();
                   if(rc.Status__c == 'Approved'){
                       ad.name = rc.resellerCustomerAccount__r.Name;
                       }
                   else{
                       ad.name = rc.Asset__r.SerialNumber;                   
                   }
                   ad.status =  rc.Status__c;
                   ad.Id= rc.resellerCustomerAccount__c;
                   ar.resellerAcctName=   rc.Reseller_Account__r.Name;   
                   ar.resellerAcctId =    rc.reseller_account__c  ;               
                   customers.add(ad);
                }
                if(rcList.size() == 0)
                {                   
                    ar.errors = 'No customer accounts';                    
                }
                ar.resellerEmail = resEmail ;
                ar.customers = customers;                
                ar.success = true;  
            }
        }
        catch(Exception e)
        {                                   
            ar.success = false;
            ar.errors = e.getMessage();           
        }
      
        return ar;
    }
    
    global class AccountResponse
    {
        global String resellerEmail;
        global String resellerAcctId;
        global String resellerAcctName;
        global List<AccountData> customers;       
        global Boolean success;
        global String errors;
    }
    global class AccountData
    {
        String name;
        String status; 
        String id;
    }
}