src/objects/RMAv2__c.object
<CustomObject>
    <description>RMA object version 2</description>
    <fields>
        <fullName>rmaAssetNrdIsInEffect__c</fullName>
        <description>Returns &quot;Yes&quot; if NRD is in effect.  Returns &quot;No&quot; otherwise.</description>
        <formula>IF(OR(ISPICKVAL(rmaComponent__c, &quot;HDD&quot;),
      ISPICKVAL(rmaComponent__c, &quot;SSD&quot;)),
   IF(ISBLANK(rmaOutgoingShipmentDateTimeOpened__c),
      IF(OR(AND(ISBLANK(rmaDiskShelfAsset__c),
                NOT(ISBLANK(rmaCaseNumber__r.Asset.assetNrdEndDate__c)),
                (TODAY() &lt;= rmaCaseNumber__r.Asset.assetNrdEndDate__c)),
            AND(NOT(ISBLANK(rmaDiskShelfAsset__c)),
                NOT(ISBLANK(rmaDiskShelfAsset__r.assetNrdEndDate__c)),
                (TODAY() &lt;= rmaDiskShelfAsset__r.assetNrdEndDate__c))),
         &quot;Yes&quot;,
         &quot;No&quot;),
      IF(OR(AND(ISBLANK(rmaDiskShelfAsset__c),
                NOT(ISBLANK(rmaCaseNumber__r.Asset.assetNrdEndDate__c)),
                (DATEVALUE(rmaOutgoingShipmentDateTimeOpened__c) &lt;= rmaCaseNumber__r.Asset.assetNrdEndDate__c)),
            AND(NOT(ISBLANK(rmaDiskShelfAsset__c)),
                NOT(ISBLANK(rmaDiskShelfAsset__r.assetNrdEndDate__c)),
                (DATEVALUE(rmaOutgoingShipmentDateTimeOpened__c) &lt;= rmaDiskShelfAsset__r.assetNrdEndDate__c))),
         &quot;Yes&quot;,
         &quot;No&quot;)),
   &quot;No&quot;)</formula>
        <label>Asset NRD Is In Effect</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>rmaAssetSla__c</fullName>
        <formula>IF(ISBLANK(rmaDiskShelfAsset__c),
   CASE(rmaCaseNumber__r.Asset.SLA__c,
        &quot;Premium&quot;, &quot;NBD&quot;,
        &quot;Premium 4 Hour&quot;, &quot;4-Hour&quot;,
        &quot;Premium 4 Hour Onsite&quot;, &quot;4-Hour Onsite&quot;,
        &quot;TSC: Premium&quot;, &quot;NBD&quot;,
        &quot;TSC: Premium Onsite&quot;, &quot;NBD Onsite&quot;,
        &quot;TSC: Premium 4 Hour&quot;, &quot;4-Hour&quot;,
        &quot;TSC: Premium 4 Hour Onsite&quot;, &quot;4-Hour Onsite&quot;,
        &quot;NBD&quot;),
   CASE(rmaDiskShelfAsset__r.SLA__c,
        &quot;Premium&quot;, &quot;NBD&quot;,
        &quot;Premium 4 Hour&quot;, &quot;4-Hour&quot;,
        &quot;Premium 4 Hour Onsite&quot;, &quot;4-Hour Onsite&quot;,
        &quot;TSC: Premium&quot;, &quot;NBD&quot;,
        &quot;TSC: Premium Onsite&quot;, &quot;NBD Onsite&quot;,
        &quot;TSC: Premium 4 Hour&quot;, &quot;4-Hour&quot;,
        &quot;TSC: Premium 4 Hour Onsite&quot;, &quot;4-Hour Onsite&quot;,
        &quot;NBD&quot;))</formula>
        <label>Asset SLA</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>rmaCaseIsEngOrExecEscalated__c</fullName>
        <formula>OR(INCLUDES(rmaCaseNumber__r.caseEscalationType__c, &quot;Engineering Escalation&quot;),
   INCLUDES(rmaCaseNumber__r.caseEscalationType__c, &quot;Executive Escalation&quot;))</formula>
        <label>Case Is Eng Or Exec Escalated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rmaComponent__c</fullName>
        <label>Component</label>
        <picklist>
            <controllingField>rmaLabArray__c</controllingField>
            <picklistValues>
                <fullName>BEZEL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CABLE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHA_NODISK (complete chassis, but without disks)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHASSIS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONT (controller)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CORD (power cord)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DONGLE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXPANDER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HBA_CARD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HDD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NIC_CARD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NVRAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PWR (power supply)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAILS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPARES (spare parts kit)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SSD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUPERCAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYS (complete system)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rmaCustomerFaRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customer FA Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rmaFaLogicHistory__c</fullName>
        <label>FA Logic History</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>rmaFaRequired__c</fullName>
        <label>FA Required</label>
        <picklist>
            <picklistValues>
                <fullName>No FA Required</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering FA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations FA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rmaOrderType__c</fullName>
        <label>Order Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>rmaOutgoingShipmentStatus__c</fullName>
        <label>Outgoing Shipment Status</label>
        <picklist>
            <controllingField>rmaType__c</controllingField>
            <picklistValues>
                <fullName>DRAFT-10: Waiting to order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPEN-10: Ordered, waiting for confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPEN-20: Order confirmed, waiting for shipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPEN-30: Shipped, waiting for delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED-10: Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANCELED-10: Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A-10: No part to ship for this RMA Type</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rmaPartFailedWithinOpsTimePeriod__c</fullName>
        <description>Returns &quot;Yes&quot; if the part failed within Operations&apos; designated time period.  Returns &quot;No&quot; otherwise.</description>
        <formula>IF(ISBLANK(rmaOutgoingShipmentDateTimeOpened__c),
   IF(OR(AND(ISBLANK(rmaDiskShelfAsset__c),
             NOT(ISBLANK(rmaCaseNumber__r.Asset.Ship_Date__c)),
             (TODAY() - rmaCaseNumber__r.Asset.Ship_Date__c &lt;= 90)),
         AND(NOT(ISBLANK(rmaDiskShelfAsset__c)),
             NOT(ISBLANK(rmaDiskShelfAsset__r.Ship_Date__c)),
             (TODAY() - rmaDiskShelfAsset__r.Ship_Date__c &lt;= 90))),
      &quot;Yes&quot;,
      &quot;No&quot;),
   IF(OR(AND(ISBLANK(rmaDiskShelfAsset__c),
             NOT(ISBLANK(rmaCaseNumber__r.Asset.Ship_Date__c)),
             (DATEVALUE(rmaOutgoingShipmentDateTimeOpened__c) - rmaCaseNumber__r.Asset.Ship_Date__c &lt;= 90)),
         AND(NOT(ISBLANK(rmaDiskShelfAsset__c)),
             NOT(ISBLANK(rmaDiskShelfAsset__r.Ship_Date__c)),
             (DATEVALUE(rmaOutgoingShipmentDateTimeOpened__c) - rmaDiskShelfAsset__r.Ship_Date__c &lt;= 90))),
      &quot;Yes&quot;,
      &quot;No&quot;))</formula>
        <label>Part Failed Within Ops Time Period</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>rmaPartIsAShipOnlyPart__c</fullName>
        <description>Returns &quot;Yes&quot; if the part is a ship-only part.  Returns &quot;No&quot; otherwise.</description>
        <formula>IF(OR(ISPICKVAL(rmaComponent__c, &quot;BEZEL&quot;),
      ISPICKVAL(rmaComponent__c, &quot;CABLE&quot;),
      ISPICKVAL(rmaComponent__c, &quot;CORD (power cord)&quot;),
      ISPICKVAL(rmaComponent__c, &quot;DONGLE&quot;),
      ISPICKVAL(rmaComponent__c, &quot;RAILS&quot;)),
   &quot;Yes&quot;,
   &quot;No&quot;)</formula>
        <label>Part Is A Ship Only Part</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>rmaRetShip2Status__c</fullName>
        <label>Ret. Ship2 Status</label>
        <picklist>
            <picklistValues>
                <fullName>DRAFT-10: Waiting to order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPEN-20: Waiting for shipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPEN-30: Shipped, waiting for delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED-10: Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED-20: Part lost by customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED-30: Part lost in shipping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED-40: Customer has &quot;no return&quot; service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED-50: Customer unable/unwilling to return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANCELED-10: Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A-10: No part to ship for this RMA Type</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rmaReturnShipmentStatus__c</fullName>
        <label>Return Shipment Status</label>
        <picklist>
            <controllingField>rmaType__c</controllingField>
            <picklistValues>
                <fullName>DRAFT-10: Waiting to order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPEN-10: Ordered, waiting for confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPEN-20: Order confirmed, waiting for shipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPEN-30: Shipped, waiting for delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED-10: Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED-20: Part lost by customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED-30: Part lost in shipping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED-40: Customer has &quot;no return&quot; service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED-50: Customer unable/unwilling to return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANCELED-10: Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A-10: No part to ship for this RMA Type</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rmaType__c</fullName>
        <label>RMA Type</label>
        <picklist>
            <picklistValues>
                <fullName>Advance replacement</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>System/part return</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RMAv2</label>
    <nameField>
        <displayFormat>RMA-{000000}</displayFormat>
        <label>RMA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMAv2s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/rmaTriggerUtilities.cls
public without sharing class rmaTriggerUtilities
  {public static void setFa(RMAv2__c rmaToProcess)
     {String newFaLogicHistory;

      System.debug('DEBUG: ****************************************');
      System.debug('DEBUG: Timestamp                           = ' + System.now());
      System.debug('DEBUG: User ID                             = ' + UserInfo.getUserId());
      System.debug('DEBUG: User Name                           = ' + UserInfo.getName());
      System.debug('DEBUG: INPUTS:');
      System.debug('DEBUG: rmaType__c                          = ' + rmaToProcess.rmaType__c);
      System.debug('DEBUG: rmaAssetNrdIsInEffect__c            = ' + rmaToProcess.rmaAssetNrdIsInEffect__c);
      System.debug('DEBUG: rmaPartIsAShipOnlyPart__c           = ' + rmaToProcess.rmaPartIsAShipOnlyPart__c);
      System.debug('DEBUG: rmaAssetSla__c                      = ' + rmaToProcess.rmaAssetSla__c);
      System.debug('DEBUG: rmaCaseIsEngOrExecEscalated__c      = ' + rmaToProcess.rmaCaseIsEngOrExecEscalated__c);
      System.debug('DEBUG: rmaComponent__c                     = ' + rmaToProcess.rmaComponent__c);
      System.debug('DEBUG: rmaPartFailedWithinOpsTimePeriod__c = ' + rmaToProcess.rmaPartFailedWithinOpsTimePeriod__c);
      System.debug('DEBUG: rmaFaRequired__c                    = ' + rmaToProcess.rmaFaRequired__c);
      System.debug('DEBUG: rmaOutgoingShipmentStatus__c        = ' + rmaToProcess.rmaOutgoingShipmentStatus__c);
      System.debug('DEBUG: rmaReturnShipmentStatus__c          = ' + rmaToProcess.rmaReturnShipmentStatus__c);
      System.debug('DEBUG: rmaRetShip2Status__c                = ' + rmaToProcess.rmaRetShip2Status__c);
      System.debug('DEBUG: rmaCustomerFaRequired__c            = ' + rmaToProcess.rmaCustomerFaRequired__c);
      System.debug('DEBUG: LOGIC DECISIONS:');

      newFaLogicHistory = rmaToProcess.rmaFaLogicHistory__c +
                          '\n****************************************\n' +
                          'Timestamp                           = ' + System.now() + '\n' +
                          'User ID                             = ' + UserInfo.getUserId() + '\n' +
                          'User Name                           = ' + UserInfo.getName() + '\n' +
                          'INPUTS:\n' +
                          'rmaType__c                          = ' + rmaToProcess.rmaType__c + '\n' +
                          'rmaAssetNrdIsInEffect__c            = ' + rmaToProcess.rmaAssetNrdIsInEffect__c + '\n' +
                          'rmaPartIsAShipOnlyPart__c           = ' + rmaToProcess.rmaPartIsAShipOnlyPart__c + '\n' +
                          'rmaAssetSla__c                      = ' + rmaToProcess.rmaAssetSla__c + '\n' +
                          'rmaCaseIsEngOrExecEscalated__c      = ' + rmaToProcess.rmaCaseIsEngOrExecEscalated__c + '\n' +
                          'rmaComponent__c                     = ' + rmaToProcess.rmaComponent__c + '\n' +
                          'rmaPartFailedWithinOpsTimePeriod__c = ' + rmaToProcess.rmaPartFailedWithinOpsTimePeriod__c + '\n' +
                          'rmaFaRequired__c                    = ' + rmaToProcess.rmaFaRequired__c + '\n' +
                          'rmaOutgoingShipmentStatus__c        = ' + rmaToProcess.rmaOutgoingShipmentStatus__c + '\n' +
                          'rmaReturnShipmentStatus__c          = ' + rmaToProcess.rmaReturnShipmentStatus__c + '\n' +
                          'rmaRetShip2Status__c                = ' + rmaToProcess.rmaRetShip2Status__c + '\n' +
                          'rmaCustomerFaRequired__c            = ' + rmaToProcess.rmaCustomerFaRequired__c + '\n' +
                          'LOGIC DECISIONS:\n';

       // Type = "System/part return"
       if (rmaToProcess.rmaType__c == 'System/part return')
         {System.debug('DEBUG: HERE 0100 - Type = "System/part return"');
          newFaLogicHistory += 'HERE 0100 - Type = "System/part return"\n';

          rmaToProcess.rmaOrderType__c          = 'System/part return';
          rmaToProcess.rmaFaRequired__c         = 'No FA Required';
          rmaToProcess.rmaCustomerFaRequired__c = false;
         }

       // Asset NRD is in Effect
       else if (rmaToProcess.rmaAssetNrdIsInEffect__c == 'Yes')
         {System.debug('DEBUG: HERE 0200 - Asset NRD is in Effect');
          newFaLogicHistory += 'HERE 0200 - Asset NRD is in Effect\n';

          if (rmaToProcess.rmaAssetSla__c.contains('Onsite'))
            {rmaToProcess.rmaOrderType__c = 'Ship Only w/ Tech';
            }
          else
            {rmaToProcess.rmaOrderType__c = 'Ship Only';
            }

          rmaToProcess.rmaFaRequired__c           = 'No FA Required';
          rmaToProcess.rmaReturnShipmentStatus__c = 'N/A-10: No part to ship for this RMA Type';
          rmaToProcess.rmaRetShip2Status__c       = 'N/A-10: No part to ship for this RMA Type';
          rmaToProcess.rmaCustomerFaRequired__c   = false;
         }

       // Part is a Ship Only Part
       else if (rmaToProcess.rmaPartIsAShipOnlyPart__c == 'Yes')
         {System.debug('DEBUG: HERE 0300 - Part is a Ship Only Part');
          newFaLogicHistory += 'HERE 0300 - Part is a Ship Only Part\n';

          if (rmaToProcess.rmaAssetSla__c.contains('Onsite'))
            {rmaToProcess.rmaOrderType__c = 'Ship Only w/ Tech';
            }
          else
            {rmaToProcess.rmaOrderType__c = 'Ship Only';
            }

          rmaToProcess.rmaFaRequired__c           = 'No FA Required';
          rmaToProcess.rmaReturnShipmentStatus__c = 'N/A-10: No part to ship for this RMA Type';
          rmaToProcess.rmaRetShip2Status__c       = 'N/A-10: No part to ship for this RMA Type';
          rmaToProcess.rmaCustomerFaRequired__c   = false;
         }

       // Case is Engineering or Executive Escalated
       // NOTE: Per Alexander Pham's flowchart, marking
       //       the FA Required field as "Engineering FA" is
       //       no longer required just because the case is
       //       escalated.  Commented this out.
       //else if (rmaToProcess.rmaCaseIsEngOrExecEscalated__c)
       //  {System.debug('DEBUG: HERE 0400 - Case is Engineering or Executive Escalated');
       //   newFaLogicHistory += 'HERE 0400 - Case is Engineering or Executive Escalated\n';
       //
       //   if (rmaToProcess.rmaAssetSla__c.contains('Onsite'))
       //     {rmaToProcess.rmaOrderType__c = 'Advance Replacement w/ FA w/ Tech';
       //     }
       //   else
       //     {rmaToProcess.rmaOrderType__c = 'Advance Replacement w/ Failure Analysis';
       //     }
       //
       //   rmaToProcess.rmaFaRequired__c = 'Engineering FA';
       //  }

       // Component = "SSD"
       else if (rmaToProcess.rmaComponent__c == 'SSD')
         {System.debug('DEBUG: HERE 0500 - Component = "SSD"');
          newFaLogicHistory += 'HERE 0500 - Component = "SSD"\n';

          if (rmaToProcess.rmaAssetSla__c.contains('Onsite'))
            {rmaToProcess.rmaOrderType__c = 'Advance Replacement w/ FA w/ Tech';
            }
          else
            {rmaToProcess.rmaOrderType__c = 'Advance Replacement w/ Failure Analysis';
            }

          rmaToProcess.rmaFaRequired__c = 'Engineering FA';
         }

       // Part Failed within Ops Time Period
       //   and
       // FA Required is not "Engineering FA"
       else if (rmaToProcess.rmaPartFailedWithinOpsTimePeriod__c == 'Yes' &&
                rmaToProcess.rmaFaRequired__c != 'Engineering FA')
         {System.debug('DEBUG: HERE 0600 - Part Failed within Ops Time Period and FA Required is not "Engineering FA"');
          newFaLogicHistory += 'HERE 0600 - Part Failed within Ops Time Period and FA Required is not "Engineering FA"\n';

          if (rmaToProcess.rmaAssetSla__c.contains('Onsite'))
            {rmaToProcess.rmaOrderType__c = 'Advance Replacement w/ FA w/ Tech';
            }
          else
            {rmaToProcess.rmaOrderType__c = 'Advance Replacement w/ Failure Analysis';
            }

          rmaToProcess.rmaFaRequired__c = 'Operations FA';
         }

       // FA Required = "Engineering FA" or "Operations FA"
       else if (rmaToProcess.rmaFaRequired__c == 'Engineering FA' ||
                rmaToProcess.rmaFaRequired__c == 'Operations FA')
         {System.debug('DEBUG: HERE 0700 - FA Required = "Engineering FA" or "Operations FA"');
          newFaLogicHistory += 'HERE 0700 - FA Required = "Engineering FA" or "Operations FA"\n';

          if (rmaToProcess.rmaAssetSla__c.contains('Onsite'))
            {rmaToProcess.rmaOrderType__c = 'Advance Replacement w/ FA w/ Tech';
            }
          else
            {rmaToProcess.rmaOrderType__c = 'Advance Replacement w/ Failure Analysis';
            }
         }

       // Asset SLA contains "Onsite"
       else if (rmaToProcess.rmaAssetSla__c.contains('Onsite'))
         {System.debug('DEBUG: HERE 0800 - Asset SLA contains "Onsite"');
          newFaLogicHistory += 'HERE 0800 - Asset SLA contains "Onsite"\n';

          rmaToProcess.rmaOrderType__c = 'Advance Replacement w/ Def Rtrn w/ Tech';
         }

       // Asset SLA does not contain "Onsite"
       // This section is the last block of logic, and will
       // catch all RMAs that didn't match earlier logic.
       else
         {System.debug('DEBUG: HERE 0900 - Asset SLA does not contain "Onsite"');
          newFaLogicHistory += 'HERE 0900 - Asset SLA does not contain "Onsite"\n';

          rmaToProcess.rmaOrderType__c = 'Advance Replacement w/ Defective Return';
         }

      System.debug('DEBUG: OUTPUTS:');
      System.debug('DEBUG: rmaOrderType__c              = ' + rmaToProcess.rmaOrderType__c);
      System.debug('DEBUG: rmaFaRequired__c             = ' + rmaToProcess.rmaFaRequired__c);
      System.debug('DEBUG: rmaOutgoingShipmentStatus__c = ' + rmaToProcess.rmaOutgoingShipmentStatus__c);
      System.debug('DEBUG: rmaReturnShipmentStatus__c   = ' + rmaToProcess.rmaReturnShipmentStatus__c);
      System.debug('DEBUG: rmaRetShip2Status__c         = ' + rmaToProcess.rmaRetShip2Status__c);
      System.debug('DEBUG: rmaCustomerFaRequired__c     = ' + rmaToProcess.rmaCustomerFaRequired__c);

      newFaLogicHistory += 'OUTPUTS:\n' +
                           'rmaOrderType__c              = ' + rmaToProcess.rmaOrderType__c + '\n' +
                           'rmaFaRequired__c             = ' + rmaToProcess.rmaFaRequired__c + '\n' +
                           'rmaOutgoingShipmentStatus__c = ' + rmaToProcess.rmaOutgoingShipmentStatus__c + '\n' +
                           'rmaReturnShipmentStatus__c   = ' + rmaToProcess.rmaReturnShipmentStatus__c + '\n' +
                           'rmaRetShip2Status__c         = ' + rmaToProcess.rmaRetShip2Status__c + '\n' +
                           'rmaCustomerFaRequired__c     = ' + rmaToProcess.rmaCustomerFaRequired__c;

      rmaToProcess.rmaFaLogicHistory__c = newFaLogicHistory.right(131072);

     }
  }