src/objects/Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <label>Tracking Number</label>
        <type>TextArea</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Shipping_Date__c</fullName>
        <description>Actual Shipping Date</description>
        <label>Actual Shipping Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BOM_Line_Number__c</fullName>
        <label>BOM Line Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <description>Product Code from Product</description>
        <formula>Product__r.ProductCode</formula>
        <label>Item</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <label>Serial Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Email_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if Shipping Email was sent on a Sales Order Line Record.</description>
        <label>Shipping Email Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <description>Tracking Number for Sales Order Line Record</description>
        <label>Tracking Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOLI-{000000}</displayFormat>
        <label>Sales Order Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/schedule_batch_shipping.cls
global class schedule_batch_shipping implements Schedulable {
    
    global void execute(SchedulableContext sc)
    {
        
        String query='Select id,Item__c,Tracking_Number__c,Quantity__c,BOM_Line_Number__c ,Start_Date__c,End_Date__c,Serial_Number__c,Sales_Order__c,Actual_Shipping_Date__c from Sales_Order_Line__c where Tracking_Number__c!=null AND Shipping_Email_Indicator__c=false ';
        batch_shipping_emails bse=new batch_shipping_emails();
        bse.query=query;
        Database.executebatch(bse,1);
    }
    
    static testMethod void myUnitTest() {
        Test.StartTest();
        schedule_batch_shipping sh1 = new schedule_batch_shipping();
        String sch = '0 0 23 * * ?';
        system.schedule('Test Territory Check', sch, sh1);
        Test.stopTest();
        integer i=1;
        System.assertEquals(i,1);
    }
    
    

}