src/objects/Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <label>Tracking Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Conversion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loaner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SoD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trunk Units</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prebuild</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Shipping_Date__c</fullName>
        <description>Actual Shipping Date</description>
        <label>Actual Shipping Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BOM_Line_Number__c</fullName>
        <label>BOM Line Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <description>Product Code from Product</description>
        <formula>Product__r.ProductCode</formula>
        <label>Item</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <label>Serial Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <description>Tracking Number for Sales Order Line Record</description>
        <label>Tracking Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOLI-{000000}</displayFormat>
        <label>Sales Order Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/test_batch_shipping_emails.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class test_batch_shipping_emails {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        List<String> idss=new List<String>();
        List<Sales_Order_Line__c> solRecs=new List<Sales_Order_Line__c>();
        
        Sales_Order__c so=new Sales_Order__c();
        so.name='Test Salesorder';
        so.Type__c='Beta';
        insert so;
        
        Sales_Order__c so1=new Sales_Order__c();
        so1.name='Test Salesorder';
        so1.Type__c='Beta';
        insert so1;
        idss.add(so.id);
        idss.add(so1.id);
        
        Sales_Order_Line__c sol=new Sales_Order_Line__c();
        sol.Sales_Order__c=so.id;
        sol.Tracking_Number__c='123';
        sol.CurrencyIsoCode='USD';
        sol.BOM_Line_Number__c='1';
        insert sol;
         Sales_Order_Line__c sol1=new Sales_Order_Line__c();
        sol1.Sales_Order__c=so.id;
        sol1.Tracking_Number__c='1234';
        sol1.CurrencyIsoCode='USD';
        sol1.BOM_Line_Number__c='1.1';
        insert sol1;
        
        solRecs.add(sol1);
        
        Sales_Order_Line__c sol2=new Sales_Order_Line__c();
        sol2.Sales_Order__c=so.id;
        sol2.Tracking_Number__c='1234';
        sol2.CurrencyIsoCode='USD';
        insert sol2;
        
        solRecs.add(sol2);
        
        Test.startTest();
        batch_shipping_emails bse=new batch_shipping_emails();
        bse.query='Select id,Item__c,Quantity__c,Serial_Number__c,Tracking_Number__c,Sales_Order__c,Actual_Shipping_Date__c from Sales_Order_Line__c';
        //bse.salesOrderIds=idss;
        bse.execute(null,solRecs);
        ID batchprocessid = Database.executeBatch(bse);
        
        Test.stopTest();
        integer i=1;
        System.assertEquals(i,1);
        
        
        
        }
        }