src/objects/Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Country__c</fullName>
        <label>Bill To Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Customer_Country__c</fullName>
        <label>End Customer Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Country__c</fullName>
        <label>Ship To Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <label>Tracking Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Conversion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loaner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SoD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trunk Units</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prebuild</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Shipping_Date__c</fullName>
        <description>Actual Shipping Date</description>
        <label>Actual Shipping Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <description>Product Code from Product</description>
        <formula>Product__r.ProductCode</formula>
        <label>Item</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <label>Serial Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Email_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if Shipping Email was sent on a Sales Order Line Record.</description>
        <label>Shipping Email Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Support_Renewal_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Support Renewal Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <description>Tracking Number for Sales Order Line Record</description>
        <label>Tracking Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOLI-{000000}</displayFormat>
        <label>Sales Order Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_Batch_Renewal_Emails.cls
@isTest

private class Test_Batch_Renewal_Emails {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        List<String> idss=new List<String>();
        List<Sales_Order_Line__c> solRecs=new List<Sales_Order_Line__c>();
        
        Sales_Order__c so=new Sales_Order__c();
        so.name='Test Salesorder';
        so.Type__c='Beta';
        so.Ship_To_Country__c='Usssssd';
        so.Bill_To_Country__c='Canada';
        so.End_Customer_Country__c='China';
        insert so;
        
        Sales_Order__c so1=new Sales_Order__c();
        so1.name='Test Salesorder';
        so1.Type__c='Beta';
        so1.Ship_To_Country__c='Usssssd';
        so1.Bill_To_Country__c='Canada';
        so1.End_Customer_Country__c='China';

        insert so1;
        idss.add(so.id);
        idss.add(so1.id);
        
        Sales_Order_Line__c sol=new Sales_Order_Line__c();
        sol.Sales_Order__c=so.id;
        sol.Tracking_Number__c='123';
        sol.CurrencyIsoCode='USD';
        sol.Support_Renewal_Indicator__c=true;
        insert sol;
        solRecs.add(sol);
        
        Test.startTest();
        BatchRenewalShippingEmails bse=new BatchRenewalShippingEmails();
        bse.query='Select id,Item__c,Tracking_Number__c,Quantity__c,Serial_Number__c,Sales_Order__c,Actual_Shipping_Date__c from Sales_Order_Line__c where Shipping_Email_Indicator__c=false AND Support_Renewal_Indicator__c=true';
        //bse.salesOrderIds=idss;
        bse.execute(null,solRecs);
        ID batchprocessid = Database.executeBatch(bse);
        
        Test.stopTest();
        integer i=1;
        System.assertEquals(i,1);
        
        
        
        }
}