src/objects/University_Course_Request__c.object
<CustomObject>
    <fields>
        <fullName>AE_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AE Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only active internal users can be selected.</errorMessage>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Only active internal users can be selected.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>University_Course_Requests3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Class_Type__c</fullName>
        <inlineHelpText>PUBLIC – open to anyone who wishes to register, will be displayed on Nimble University
PRIVATE – only available to attendees with private registration link, will not be displayed on Nimble University</inlineHelpText>
        <label>Class Type</label>
        <picklist>
            <picklistValues>
                <fullName>Public</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Desired_Course_Date_Start_Time__c</fullName>
        <inlineHelpText>The start date/time should be 08:30 AM - 09:30 AM in the venue’s local time.</inlineHelpText>
        <label>Desired Course Date &amp; Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Projector_Required__c</fullName>
        <inlineHelpText>Do you require a projector rental at the venue for you? (We recommend you bring a projector with you if you have one.)</inlineHelpText>
        <label>Projector Required</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Requested_Instructor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Please consult with your SE Manager to find an instructor</inlineHelpText>
        <label>Requested Instructor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only active internal users can be selected. User must be a systems engineer and a certified instructor.</errorMessage>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>User.Certified_Instructor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Only active internal users can be selected. User must be a systems engineer and a certified instructor.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>University_Course_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requester_City__c</fullName>
        <label>Requester City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requester_Country__c</fullName>
        <label>Requester Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requester_State__c</fullName>
        <label>Requester State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SE_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SE Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only active internal users can be selected.</errorMessage>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Only active internal users can be selected.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>University_Course_Requests4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Venue_City__c</fullName>
        <label>Venue City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>University Course Request</label>
    <nameField>
        <displayFormat>UCR-{0000}</displayFormat>
        <label>University Course Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>University Course Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UniversityCourseRequestTest.cls
/**
 * Test class for: UniversityCourseRequest.cls and GoogleServices.cls
 * @Author : Bunhor
 * @CreatedDate : 10-May-15 
 */
@isTest
private class UniversityCourseRequestTest {
	static University_Course_Request__c courseReq;
	
	static void setupData(){ 
		courseReq = new University_Course_Request__c();
		courseReq.Desired_Course_Date_Start_Time__c = UniversityCourseRequest.getDateTimeAtNparam(system.now(), 9);
		courseReq.Requester_City__c = 'San Francisco';
		courseReq.Venue_City__c = 'San Francisco';
		courseReq.Requester_State__c = 'CA';
		courseReq.Requester_Country__c = 'USA';
		courseReq.Class_Type__c = 'Public';
		courseReq.Requested_Instructor__c = null;
		courseReq.AE_Name__c = null;
		courseReq.SE_Name__c = null;
		courseReq.Projector_Required__c = 'Yes'; 
	}
	 
    static testMethod void insertUniversityCourseRequest() {  
        setupData();
        System.debug('=============='+courseReq.Desired_Course_Date_Start_Time__c);
        Test.startTest();
        insert courseReq; // the logic are fired when inserting asynchronously
        Test.stopTest();
        // asserting   
    }
}